import { COUNTRY_NAMES, DEFAULT_COUNTRY_NAME } from './location-catalog';

export const USER_COUNTRY_STORAGE_KEY = 'urbanfix_selected_country';
export const USER_COUNTRY_COOKIE_KEY = 'urbanfix_selected_country';
export const USER_COUNTRY_EVENT_NAME = 'country_selected';
export const USER_COUNTRY_CHANGED_EVENT = 'urbanfix_country_changed';

const normalizeCountryText = (value: unknown) =>
  String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();

const RECOGNIZED_COUNTRY_OPTIONS = [
  'Afganistan',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaiyan',
  'Bahamas',
  'Bangladesh',
  'Barbados',
  'Barein',
  'Belgica',
  'Belice',
  'Benin',
  'Bielorrusia',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Butan',
  'Cabo Verde',
  'Camboya',
  'Camerun',
  'Canada',
  'Catar',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Colombia',
  'Comoras',
  'Corea del Norte',
  'Corea del Sur',
  'Costa de Marfil',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Arabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'Espana',
  'Estados Unidos',
  'Estonia',
  'Esuatini',
  'Etiopia',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Ghana',
  'Granada',
  'Grecia',
  'Guatemala',
  'Guinea',
  'Guinea Ecuatorial',
  'Guinea-Bisau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungria',
  'India',
  'Indonesia',
  'Irak',
  'Iran',
  'Irlanda',
  'Islandia',
  'Islas Marshall',
  'Islas Salomon',
  'Israel',
  'Italia',
  'Jamaica',
  'Japon',
  'Jordania',
  'Kazajistan',
  'Kenia',
  'Kirguistan',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letonia',
  'Libano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macedonia del Norte',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Mauricio',
  'Mauritania',
  'Mexico',
  'Micronesia',
  'Moldavia',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Noruega',
  'Nueva Zelanda',
  'Oman',
  'Paises Bajos',
  'Pakistan',
  'Palaos',
  'Palestina',
  'Panama',
  'Papua Nueva Guinea',
  'Paraguay',
  'Peru',
  'Polonia',
  'Portugal',
  'Reino Unido',
  'Republica Centroafricana',
  'Republica Checa',
  'Republica del Congo',
  'Republica Democratica del Congo',
  'Republica Dominicana',
  'Ruanda',
  'Rumania',
  'Rusia',
  'Samoa',
  'San Cristobal y Nieves',
  'San Marino',
  'San Vicente y las Granadinas',
  'Santa Lucia',
  'Santo Tome y Principe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Sudafrica',
  'Sudan',
  'Sudan del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Tailandia',
  'Tanzania',
  'Tayikistan',
  'Timor Oriental',
  'Togo',
  'Tonga',
  'Trinidad y Tobago',
  'Tunez',
  'Turkmenistan',
  'Turquia',
  'Tuvalu',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vaticano',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
];

const COUNTRY_FLAG_CODES: Record<string, string> = {
  Afganistan: 'AF',
  Albania: 'AL',
  Alemania: 'DE',
  Andorra: 'AD',
  Angola: 'AO',
  'Antigua y Barbuda': 'AG',
  'Arabia Saudita': 'SA',
  Argelia: 'DZ',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaiyan: 'AZ',
  Bahamas: 'BS',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Barein: 'BH',
  Belgica: 'BE',
  Belice: 'BZ',
  Benin: 'BJ',
  Bielorrusia: 'BY',
  Bolivia: 'BO',
  'Bosnia y Herzegovina': 'BA',
  Botsuana: 'BW',
  Brasil: 'BR',
  Brunei: 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Butan: 'BT',
  'Cabo Verde': 'CV',
  Camboya: 'KH',
  Camerun: 'CM',
  Canada: 'CA',
  Catar: 'QA',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  Chipre: 'CY',
  Colombia: 'CO',
  Comoras: 'KM',
  'Corea del Norte': 'KP',
  'Corea del Sur': 'KR',
  'Costa de Marfil': 'CI',
  'Costa Rica': 'CR',
  Croacia: 'HR',
  Cuba: 'CU',
  Dinamarca: 'DK',
  Dominica: 'DM',
  Ecuador: 'EC',
  Egipto: 'EG',
  'El Salvador': 'SV',
  'Emiratos Arabes Unidos': 'AE',
  Eritrea: 'ER',
  Eslovaquia: 'SK',
  Eslovenia: 'SI',
  Espana: 'ES',
  'Estados Unidos': 'US',
  Estonia: 'EE',
  Esuatini: 'SZ',
  Etiopia: 'ET',
  Filipinas: 'PH',
  Finlandia: 'FI',
  Fiyi: 'FJ',
  Francia: 'FR',
  Gabon: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Ghana: 'GH',
  Granada: 'GD',
  Grecia: 'GR',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea Ecuatorial': 'GQ',
  'Guinea-Bisau': 'GW',
  Guyana: 'GY',
  Haiti: 'HT',
  Honduras: 'HN',
  Hungria: 'HU',
  India: 'IN',
  Indonesia: 'ID',
  Irak: 'IQ',
  Iran: 'IR',
  Irlanda: 'IE',
  Islandia: 'IS',
  'Islas Marshall': 'MH',
  'Islas Salomon': 'SB',
  Israel: 'IL',
  Italia: 'IT',
  Jamaica: 'JM',
  Japon: 'JP',
  Jordania: 'JO',
  Kazajistan: 'KZ',
  Kenia: 'KE',
  Kirguistan: 'KG',
  Kiribati: 'KI',
  Kuwait: 'KW',
  Laos: 'LA',
  Lesoto: 'LS',
  Letonia: 'LV',
  Libano: 'LB',
  Liberia: 'LR',
  Libia: 'LY',
  Liechtenstein: 'LI',
  Lituania: 'LT',
  Luxemburgo: 'LU',
  'Macedonia del Norte': 'MK',
  Madagascar: 'MG',
  Malasia: 'MY',
  Malaui: 'MW',
  Maldivas: 'MV',
  Mali: 'ML',
  Malta: 'MT',
  Marruecos: 'MA',
  Mauricio: 'MU',
  Mauritania: 'MR',
  Mexico: 'MX',
  Micronesia: 'FM',
  Moldavia: 'MD',
  Monaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Mozambique: 'MZ',
  Myanmar: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Noruega: 'NO',
  'Nueva Zelanda': 'NZ',
  Oman: 'OM',
  'Paises Bajos': 'NL',
  Pakistan: 'PK',
  Palaos: 'PW',
  Palestina: 'PS',
  Panama: 'PA',
  'Papua Nueva Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Polonia: 'PL',
  Portugal: 'PT',
  'Reino Unido': 'GB',
  'Republica Centroafricana': 'CF',
  'Republica Checa': 'CZ',
  'Republica del Congo': 'CG',
  'Republica Democratica del Congo': 'CD',
  'Republica Dominicana': 'DO',
  Ruanda: 'RW',
  Rumania: 'RO',
  Rusia: 'RU',
  Samoa: 'WS',
  'San Cristobal y Nieves': 'KN',
  'San Marino': 'SM',
  'San Vicente y las Granadinas': 'VC',
  'Santa Lucia': 'LC',
  'Santo Tome y Principe': 'ST',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  'Sierra Leona': 'SL',
  Singapur: 'SG',
  Siria: 'SY',
  Somalia: 'SO',
  'Sri Lanka': 'LK',
  Sudafrica: 'ZA',
  Sudan: 'SD',
  'Sudan del Sur': 'SS',
  Suecia: 'SE',
  Suiza: 'CH',
  Surinam: 'SR',
  Tailandia: 'TH',
  Tanzania: 'TZ',
  Tayikistan: 'TJ',
  'Timor Oriental': 'TL',
  Togo: 'TG',
  Tonga: 'TO',
  'Trinidad y Tobago': 'TT',
  Tunez: 'TN',
  Turkmenistan: 'TM',
  Turquia: 'TR',
  Tuvalu: 'TV',
  Ucrania: 'UA',
  Uganda: 'UG',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  Vaticano: 'VA',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Yemen: 'YE',
  Yibuti: 'DJ',
  Zambia: 'ZM',
  Zimbabue: 'ZW',
};

const COUNTRY_FLAG_CODES_BY_NORMALIZED = Object.fromEntries(
  Object.entries(COUNTRY_FLAG_CODES).map(([country, code]) => [normalizeCountryText(country), code])
);

const countryCodeToFlagEmoji = (code: string) =>
  code
    .toUpperCase()
    .replace(/[A-Z]/g, (letter) => String.fromCodePoint(127397 + letter.charCodeAt(0)));

export const COUNTRY_SELECTION_OPTIONS = Array.from(new Set([...COUNTRY_NAMES, ...RECOGNIZED_COUNTRY_OPTIONS]));

export const normalizeCountryPreference = (value: unknown) => {
  const normalized = normalizeCountryText(value);
  if (!normalized) return '';
  return COUNTRY_SELECTION_OPTIONS.find((country) => normalizeCountryText(country) === normalized) || '';
};

export const getCountryFlagEmoji = (country: unknown) => {
  const code = COUNTRY_FLAG_CODES_BY_NORMALIZED[normalizeCountryText(country)];
  return code ? countryCodeToFlagEmoji(code) : '\u{1F310}';
};

export const getCountryFlagCode = (country: unknown) =>
  COUNTRY_FLAG_CODES_BY_NORMALIZED[normalizeCountryText(country)] || '';

export const getCountryOptionLabel = (country: string) => `${getCountryFlagEmoji(country)} ${country}`;

export const getStoredCountryPreference = () => {
  if (typeof window === 'undefined') return '';
  try {
    return normalizeCountryPreference(window.localStorage.getItem(USER_COUNTRY_STORAGE_KEY));
  } catch {
    return '';
  }
};

export const storeCountryPreference = (country: string) => {
  if (typeof window === 'undefined') return '';
  const normalized = normalizeCountryPreference(country) || DEFAULT_COUNTRY_NAME;
  try {
    window.localStorage.setItem(USER_COUNTRY_STORAGE_KEY, normalized);
  } catch {
    // The selection still applies for the current page even if storage is unavailable.
  }
  try {
    window.document.cookie = `${USER_COUNTRY_COOKIE_KEY}=${encodeURIComponent(
      normalized
    )}; path=/; max-age=31536000; samesite=lax`;
  } catch {
    // The selected country remains available in local storage if cookies are unavailable.
  }
  try {
    window.dispatchEvent(new CustomEvent(USER_COUNTRY_CHANGED_EVENT, { detail: { country: normalized } }));
  } catch {
    // Ignore event dispatch issues in older browsers.
  }
  return normalized;
};
