export type GlobalLocalityOption = {
  name: string;
  label?: string;
};

export const GLOBAL_LOCALITY_OPTIONS_BY_COUNTRY_PROVINCE: Record<string, GlobalLocalityOption[]> = {
  'AR|ciudad autonoma de buenos aires': [
    { name: 'Agronomia' },
    { name: 'Almagro' },
    { name: 'Balvanera' },
    { name: 'Barracas' },
    { name: 'Belgrano' },
    { name: 'Boedo' },
    { name: 'Caballito' },
    { name: 'Chacarita' },
    { name: 'Coghlan' },
    { name: 'Colegiales' },
    { name: 'Constitucion' },
    { name: 'Flores' },
    { name: 'Floresta' },
    { name: 'La Boca' },
    { name: 'La Paternal' },
    { name: 'Liniers' },
    { name: 'Mataderos' },
    { name: 'Monte Castro' },
    { name: 'Montserrat' },
    { name: 'Nueva Pompeya' },
    { name: 'Nunez' },
    { name: 'Palermo' },
    { name: 'Parque Avellaneda' },
    { name: 'Parque Chacabuco' },
    { name: 'Parque Chas' },
    { name: 'Parque Patricios' },
    { name: 'Puerto Madero' },
    { name: 'Recoleta' },
    { name: 'Retiro' },
    { name: 'Saavedra' },
    { name: 'San Cristobal' },
    { name: 'San Nicolas' },
    { name: 'San Telmo' },
    { name: 'Velez Sarsfield' },
    { name: 'Versalles' },
    { name: 'Villa Crespo' },
    { name: 'Villa del Parque' },
    { name: 'Villa Devoto' },
    { name: 'Villa General Mitre' },
    { name: 'Villa Lugano' },
    { name: 'Villa Luro' },
    { name: 'Villa Ortuzar' },
    { name: 'Villa Pueyrredon' },
    { name: 'Villa Real' },
    { name: 'Villa Riachuelo' },
    { name: 'Villa Santa Rita' },
    { name: 'Villa Soldati' },
    { name: 'Villa Urquiza' },
  ],
  'UY|montevideo': [{ name: 'Montevideo' }, { name: 'Ciudad Vieja' }, { name: 'Centro' }, { name: 'Pocitos' }, { name: 'Punta Carretas' }, { name: 'Malvin' }],
  'UY|canelones': [{ name: 'Canelones' }, { name: 'Las Piedras' }, { name: 'Ciudad de la Costa' }, { name: 'Pando' }, { name: 'Atlantida' }],
  'UY|maldonado': [{ name: 'Maldonado' }, { name: 'Punta del Este' }, { name: 'San Carlos' }, { name: 'Piriapolis' }],
  'UY|colonia': [{ name: 'Colonia del Sacramento' }, { name: 'Carmelo' }, { name: 'Nueva Helvecia' }, { name: 'Juan Lacaze' }],
  'UY|salto': [{ name: 'Salto' }, { name: 'Dayman' }, { name: 'Constitucion' }],
  'UY|paysandu': [{ name: 'Paysandu' }, { name: 'Guichon' }, { name: 'Quebracho' }],
  'UY|rivera': [{ name: 'Rivera' }, { name: 'Tranqueras' }, { name: 'Vichadero' }],
  'UY|rocha': [{ name: 'Rocha' }, { name: 'La Paloma' }, { name: 'Chuy' }, { name: 'Castillos' }],
  'UY|san jose': [{ name: 'San Jose de Mayo' }, { name: 'Libertad' }, { name: 'Ciudad del Plata' }],
  'UY|soriano': [{ name: 'Mercedes' }, { name: 'Dolores' }, { name: 'Cardona' }],
  'UY|tacuarembo': [{ name: 'Tacuarembo' }, { name: 'Paso de los Toros' }, { name: 'San Gregorio de Polanco' }],
  'CL|metropolitana de santiago': [{ name: 'Santiago' }, { name: 'Providencia' }, { name: 'Las Condes' }, { name: 'Nunoa' }, { name: 'Maipu' }, { name: 'Puente Alto' }],
  'CL|valparaiso': [{ name: 'Valparaiso' }, { name: 'Vina del Mar' }, { name: 'Quilpue' }, { name: 'Villa Alemana' }, { name: 'San Antonio' }],
  'CL|biobio': [{ name: 'Concepcion' }, { name: 'Talcahuano' }, { name: 'Los Angeles' }, { name: 'Coronel' }],
  'CL|la araucania': [{ name: 'Temuco' }, { name: 'Villarrica' }, { name: 'Padre Las Casas' }, { name: 'Angol' }],
  'CL|los lagos': [{ name: 'Puerto Montt' }, { name: 'Osorno' }, { name: 'Castro' }, { name: 'Ancud' }],
  'CL|coquimbo': [{ name: 'La Serena' }, { name: 'Coquimbo' }, { name: 'Ovalle' }, { name: 'Illapel' }],
  'CL|antofagasta': [{ name: 'Antofagasta' }, { name: 'Calama' }, { name: 'Tocopilla' }],
  'CL|maule': [{ name: 'Talca' }, { name: 'Curico' }, { name: 'Linares' }, { name: 'Cauquenes' }],
  'PY|asuncion': [{ name: 'Asuncion' }],
  'PY|central': [{ name: 'San Lorenzo' }, { name: 'Luque' }, { name: 'Fernando de la Mora' }, { name: 'Capiata' }, { name: 'Lambare' }],
  'PY|alto parana': [{ name: 'Ciudad del Este' }, { name: 'Presidente Franco' }, { name: 'Hernandarias' }, { name: 'Minga Guazu' }],
  'PY|itapua': [{ name: 'Encarnacion' }, { name: 'Cambyreta' }, { name: 'Coronel Bogado' }],
  'PY|caaguazu': [{ name: 'Coronel Oviedo' }, { name: 'Caaguazu' }, { name: 'J. Eulogio Estigarribia' }],
  'BO|la paz': [{ name: 'La Paz' }, { name: 'El Alto' }, { name: 'Viacha' }, { name: 'Achocalla' }],
  'BO|santa cruz': [{ name: 'Santa Cruz de la Sierra' }, { name: 'Montero' }, { name: 'Warnes' }, { name: 'Cotoca' }],
  'BO|cochabamba': [{ name: 'Cochabamba' }, { name: 'Quillacollo' }, { name: 'Sacaba' }, { name: 'Tiquipaya' }],
  'BO|tarija': [{ name: 'Tarija' }, { name: 'Yacuiba' }, { name: 'Bermejo' }],
  'BO|chuquisaca': [{ name: 'Sucre' }, { name: 'Monteagudo' }, { name: 'Camargo' }],
  'BR|sao paulo': [{ name: 'Sao Paulo' }, { name: 'Campinas' }, { name: 'Santos' }, { name: 'Guarulhos' }, { name: 'Santo Andre' }],
  'BR|rio de janeiro': [{ name: 'Rio de Janeiro' }, { name: 'Niteroi' }, { name: 'Petropolis' }, { name: 'Duque de Caxias' }],
  'BR|minas gerais': [{ name: 'Belo Horizonte' }, { name: 'Uberlandia' }, { name: 'Contagem' }, { name: 'Juiz de Fora' }],
  'BR|parana': [{ name: 'Curitiba' }, { name: 'Londrina' }, { name: 'Maringa' }, { name: 'Ponta Grossa' }],
  'BR|rio grande do sul': [{ name: 'Porto Alegre' }, { name: 'Caxias do Sul' }, { name: 'Pelotas' }, { name: 'Canoas' }],
  'BR|santa catarina': [{ name: 'Florianopolis' }, { name: 'Joinville' }, { name: 'Blumenau' }, { name: 'Chapeco' }],
  'BR|bahia': [{ name: 'Salvador' }, { name: 'Feira de Santana' }, { name: 'Vitoria da Conquista' }],
  'BR|pernambuco': [{ name: 'Recife' }, { name: 'Olinda' }, { name: 'Caruaru' }, { name: 'Jaboatao dos Guararapes' }],
  'PE|lima': [{ name: 'Lima' }, { name: 'Miraflores' }, { name: 'San Isidro' }, { name: 'Santiago de Surco' }, { name: 'Callao' }],
  'PE|arequipa': [{ name: 'Arequipa' }, { name: 'Cayma' }, { name: 'Cerro Colorado' }, { name: 'Yanahuara' }],
  'PE|cusco': [{ name: 'Cusco' }, { name: 'San Sebastian' }, { name: 'Santiago' }, { name: 'Wanchaq' }],
  'PE|la libertad': [{ name: 'Trujillo' }, { name: 'El Porvenir' }, { name: 'La Esperanza' }, { name: 'Victor Larco Herrera' }],
  'PE|piura': [{ name: 'Piura' }, { name: 'Sullana' }, { name: 'Talara' }, { name: 'Paita' }],
  'CO|bogota d.c.': [{ name: 'Bogota' }, { name: 'Chapinero' }, { name: 'Usaquen' }, { name: 'Suba' }, { name: 'Kennedy' }],
  'CO|antioquia': [{ name: 'Medellin' }, { name: 'Bello' }, { name: 'Envigado' }, { name: 'Itagui' }, { name: 'Rionegro' }],
  'CO|valle del cauca': [{ name: 'Cali' }, { name: 'Palmira' }, { name: 'Buenaventura' }, { name: 'Tulua' }],
  'CO|atlantico': [{ name: 'Barranquilla' }, { name: 'Soledad' }, { name: 'Malambo' }, { name: 'Puerto Colombia' }],
  'CO|santander': [{ name: 'Bucaramanga' }, { name: 'Floridablanca' }, { name: 'Giron' }, { name: 'Piedecuesta' }],
  'CO|cundinamarca': [{ name: 'Soacha' }, { name: 'Chia' }, { name: 'Zipaquira' }, { name: 'Facatativa' }, { name: 'Fusagasuga' }],
  'MX|ciudad de mexico': [{ name: 'Alvaro Obregon' }, { name: 'Benito Juarez' }, { name: 'Coyoacan' }, { name: 'Cuauhtemoc' }, { name: 'Miguel Hidalgo' }, { name: 'Tlalpan' }],
  'MX|jalisco': [{ name: 'Guadalajara' }, { name: 'Zapopan' }, { name: 'Tlaquepaque' }, { name: 'Tonala' }],
  'MX|nuevo leon': [{ name: 'Monterrey' }, { name: 'San Pedro Garza Garcia' }, { name: 'Guadalupe' }, { name: 'San Nicolas de los Garza' }],
  'MX|estado de mexico': [{ name: 'Toluca' }, { name: 'Ecatepec' }, { name: 'Naucalpan' }, { name: 'Tlalnepantla' }, { name: 'Nezahualcoyotl' }],
  'MX|puebla': [{ name: 'Puebla' }, { name: 'Tehuacan' }, { name: 'San Andres Cholula' }, { name: 'San Pedro Cholula' }],
  'MX|queretaro': [{ name: 'Queretaro' }, { name: 'San Juan del Rio' }, { name: 'El Marques' }, { name: 'Corregidora' }],
  'US|california': [{ name: 'Los Angeles' }, { name: 'San Diego' }, { name: 'San Jose' }, { name: 'San Francisco' }, { name: 'Sacramento' }],
  'US|florida': [{ name: 'Miami' }, { name: 'Orlando' }, { name: 'Tampa' }, { name: 'Jacksonville' }, { name: 'Fort Lauderdale' }],
  'US|texas': [{ name: 'Houston' }, { name: 'Dallas' }, { name: 'Austin' }, { name: 'San Antonio' }, { name: 'Fort Worth' }],
  'US|new york': [{ name: 'New York City' }, { name: 'Buffalo' }, { name: 'Rochester' }, { name: 'Yonkers' }, { name: 'Syracuse' }],
  'US|illinois': [{ name: 'Chicago' }, { name: 'Aurora' }, { name: 'Naperville' }, { name: 'Joliet' }],
  'US|georgia': [{ name: 'Atlanta' }, { name: 'Augusta' }, { name: 'Savannah' }, { name: 'Columbus' }],
  'US|north carolina': [{ name: 'Charlotte' }, { name: 'Raleigh' }, { name: 'Greensboro' }, { name: 'Durham' }],
  'US|washington': [{ name: 'Seattle' }, { name: 'Spokane' }, { name: 'Tacoma' }, { name: 'Vancouver' }],
  'CA|ontario': [{ name: 'Toronto' }, { name: 'Ottawa' }, { name: 'Mississauga' }, { name: 'Hamilton' }, { name: 'London' }],
  'CA|quebec': [{ name: 'Montreal' }, { name: 'Quebec City' }, { name: 'Laval' }, { name: 'Gatineau' }],
  'CA|british columbia': [{ name: 'Vancouver' }, { name: 'Victoria' }, { name: 'Surrey' }, { name: 'Burnaby' }],
  'CA|alberta': [{ name: 'Calgary' }, { name: 'Edmonton' }, { name: 'Red Deer' }, { name: 'Lethbridge' }],
  'ES|madrid': [{ name: 'Madrid' }, { name: 'Alcala de Henares' }, { name: 'Getafe' }, { name: 'Leganes' }],
  'ES|cataluna': [{ name: 'Barcelona' }, { name: 'Hospitalet de Llobregat' }, { name: 'Badalona' }, { name: 'Terrassa' }, { name: 'Sabadell' }],
  'ES|andalucia': [{ name: 'Sevilla' }, { name: 'Malaga' }, { name: 'Cordoba' }, { name: 'Granada' }, { name: 'Cadiz' }],
  'ES|comunidad valenciana': [{ name: 'Valencia' }, { name: 'Alicante' }, { name: 'Castellon de la Plana' }, { name: 'Elche' }],
};
