export const GLOBAL_PROVINCE_OPTIONS_BY_CODE: Record<string, string[]> = {
  AD: [
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julià de Lòria",
  ],
  AE: [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al Quwain",
  ],
  AF: [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daykundi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghōr",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Kunduz Province",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimruz",
    "Nuristan",
    "Paktia",
    "Paktika",
    "Panjshir",
    "Parwan",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Urozgan",
    "Zabul",
  ],
  AG: [
    "Barbuda",
    "Redonda",
    "Saint George Parish",
    "Saint John Parish",
    "Saint Mary Parish",
    "Saint Paul Parish",
    "Saint Peter Parish",
    "Saint Philip Parish",
  ],
  AI: [
  ],
  AL: [
    "Berat County",
    "Berat District",
    "Bulqizë District",
    "Delvinë District",
    "Devoll District",
    "Dibër County",
    "Dibër District",
    "Durrës County",
    "Durrës District",
    "Elbasan County",
    "Fier County",
    "Fier District",
    "Gjirokastër County",
    "Gjirokastër District",
    "Gramsh District",
    "Has District",
    "Kavajë District",
    "Kolonjë District",
    "Korçë County",
    "Korçë District",
    "Krujë District",
    "Kuçovë District",
    "Kukës County",
    "Kukës District",
    "Kurbin District",
    "Lezhë County",
    "Lezhë District",
    "Librazhd District",
    "Lushnjë District",
    "Malësi e Madhe District",
    "Mallakastër District",
    "Mat District",
    "Mirditë District",
    "Peqin District",
    "Përmet District",
    "Pogradec District",
    "Pukë District",
    "Sarandë District",
    "Shkodër County",
    "Shkodër District",
    "Skrapar District",
    "Tepelenë District",
    "Tirana County",
    "Tirana District",
    "Tropojë District",
    "Vlorë County",
    "Vlorë District",
  ],
  AM: [
    "Aragatsotn Region",
    "Ararat Province",
    "Armavir Region",
    "Gegharkunik Province",
    "Kotayk Region",
    "Lori Region",
    "Shirak Region",
    "Syunik Province",
    "Tavush Region",
    "Vayots Dzor Region",
    "Yerevan",
  ],
  AN: [
    "Bonaire",
    "Saba",
    "Sint Eustatius",
  ],
  AO: [
    "Bengo Province",
    "Benguela Province",
    "Bié Province",
    "Cabinda Province",
    "Cuando Cubango Province",
    "Cuanza Norte Province",
    "Cuanza Sul",
    "Cunene Province",
    "Huambo Province",
    "Huíla Province",
    "Luanda Province",
    "Lunda Norte Province",
    "Lunda Sul Province",
    "Malanje Province",
    "Moxico Province",
    "Uíge Province",
    "Zaire Province",
  ],
  AQ: [
  ],
  AR: [
    "Autonomous City Of Buenos Aires",
    "Buenos Aires Province",
    "Catamarca Province",
    "Chaco Province",
    "Chubut Province",
    "Córdoba Province",
    "Corrientes",
    "Entre Ríos Province",
    "Formosa Province",
    "Jujuy Province",
    "La Pampa",
    "La Rioja Province",
    "Mendoza",
    "Misiones Province",
    "Neuquén Province",
    "Río Negro Province",
    "Salta Province",
    "San Juan Province",
    "San Luis Province",
    "Santa Cruz Province",
    "Santa Fe Province",
    "Santiago del Estero Province",
    "Tierra del Fuego Province",
    "Tucumán Province",
  ],
  AT: [
    "Burgenland",
    "Carinthia",
    "Lower Austria",
    "Salzburg",
    "Styria",
    "Tyrol",
    "Upper Austria",
    "Vienna",
    "Vorarlberg",
  ],
  AU: [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
  ],
  AW: [
  ],
  AX: [
  ],
  AZ: [
    "Absheron District",
    "Agdam District",
    "Agdash District",
    "Aghjabadi District",
    "Agstafa District",
    "Agsu District",
    "Astara District",
    "Babek District",
    "Baku",
    "Balakan District",
    "Barda District",
    "Beylagan District",
    "Bilasuvar District",
    "Dashkasan District",
    "Fizuli District",
    "Ganja",
    "Gədəbəy",
    "Gobustan District",
    "Goranboy District",
    "Goychay",
    "Goygol District",
    "Hajigabul District",
    "Imishli District",
    "Ismailli District",
    "Jabrayil District",
    "Jalilabad District",
    "Julfa District",
    "Kalbajar District",
    "Kangarli District",
    "Khachmaz District",
    "Khizi District",
    "Khojali District",
    "Kurdamir District",
    "Lachin District",
    "Lankaran",
    "Lankaran District",
    "Lerik District",
    "Martuni",
    "Masally District",
    "Mingachevir",
    "Nakhchivan Autonomous Republic",
    "Neftchala District",
    "Oghuz District",
    "Ordubad District",
    "Qabala District",
    "Qakh District",
    "Qazakh District",
    "Quba District",
    "Qubadli District",
    "Qusar District",
    "Saatly District",
    "Sabirabad District",
    "Sadarak District",
    "Salyan District",
    "Samukh District",
    "Shabran District",
    "Shahbuz District",
    "Shaki",
    "Shaki District",
    "Shamakhi District",
    "Shamkir District",
    "Sharur District",
    "Shirvan",
    "Shusha District",
    "Siazan District",
    "Sumqayit",
    "Tartar District",
    "Tovuz District",
    "Ujar District",
    "Yardymli District",
    "Yevlakh",
    "Yevlakh District",
    "Zangilan District",
    "Zaqatala District",
    "Zardab District",
  ],
  BA: [
    "Bosnian Podrinje Canton",
    "Brčko District",
    "Canton 10",
    "Central Bosnia Canton",
    "Federation of Bosnia and Herzegovina",
    "Herzegovina-Neretva Canton",
    "Posavina Canton",
    "Republika Srpska",
    "Sarajevo Canton",
    "Tuzla Canton",
    "Una-Sana Canton",
    "West Herzegovina Canton",
    "Zenica-Doboj Canton",
  ],
  BB: [
    "Christ Church",
    "Saint Andrew",
    "Saint George",
    "Saint James",
    "Saint John",
    "Saint Joseph",
    "Saint Lucy",
    "Saint Michael",
    "Saint Peter",
    "Saint Philip",
    "Saint Thomas",
  ],
  BD: [
    "Barisal",
    "Chittagong",
    "Dhaka",
    "Khulna",
    "Mymensingh",
    "Rajshahi",
    "Rangpur",
    "Sylhet",
  ],
  BE: [
    "Antwerp",
    "Brussels-Capital Region",
    "East Flanders",
    "Flemish Brabant",
    "Hainaut",
    "Liege",
    "Limburg",
    "Luxembourg",
    "Namur",
    "Walloon Brabant",
    "West Flanders",
  ],
  BF: [
    "Balé Province",
    "Bam Province",
    "Banwa Province",
    "Bazèga Province",
    "Boucle du Mouhoun Region",
    "Bougouriba Province",
    "Boulgou",
    "Cascades Region",
    "Centre",
    "Centre-Est Region",
    "Centre-Nord Region",
    "Centre-Ouest Region",
    "Centre-Sud Region",
    "Comoé Province",
    "Est Region",
    "Ganzourgou Province",
    "Gnagna Province",
    "Gourma Province",
    "Hauts-Bassins Region",
    "Houet Province",
    "Ioba Province",
    "Kadiogo Province",
    "Kénédougou Province",
    "Komondjari Province",
    "Kompienga Province",
    "Kossi Province",
    "Koulpélogo Province",
    "Kouritenga Province",
    "Kourwéogo Province",
    "Léraba Province",
    "Loroum Province",
    "Mouhoun",
    "Nahouri Province",
    "Namentenga Province",
    "Nayala Province",
    "Nord Region, Burkina Faso",
    "Noumbiel Province",
    "Oubritenga Province",
    "Oudalan Province",
    "Passoré Province",
    "Plateau-Central Region",
    "Poni Province",
    "Sahel Region",
    "Sanguié Province",
    "Sanmatenga Province",
    "Séno Province",
    "Sissili Province",
    "Soum Province",
    "Sourou Province",
    "Sud-Ouest Region",
    "Tapoa Province",
    "Tuy Province",
    "Yagha Province",
    "Yatenga Province",
    "Ziro Province",
    "Zondoma Province",
    "Zoundwéogo Province",
  ],
  BG: [
    "Blagoevgrad Province",
    "Burgas Province",
    "Dobrich Province",
    "Gabrovo Province",
    "Haskovo Province",
    "Kardzhali Province",
    "Kyustendil Province",
    "Lovech Province",
    "Montana Province",
    "Pazardzhik Province",
    "Pernik Province",
    "Pleven Province",
    "Plovdiv Province",
    "Razgrad Province",
    "Ruse Province",
    "Silistra Province",
    "Sliven Province",
    "Smolyan Province",
    "Sofia City Province",
    "Sofia Province",
    "Stara Zagora Province",
    "Targovishte Province",
    "Varna Province",
    "Veliko Tarnovo Province",
    "Vidin Province",
    "Vratsa Province",
    "Yambol Province",
  ],
  BH: [
    "Capital Governorate",
    "Central Governorate",
    "Muharraq Governorate",
    "Northern Governorate",
    "Southern Governorate",
  ],
  BI: [
    "Bubanza Province",
    "Bujumbura Mairie Province",
    "Bujumbura Rural Province",
    "Bururi Province",
    "Cankuzo Province",
    "Cibitoke Province",
    "Gitega Province",
    "Karuzi Province",
    "Kayanza Province",
    "Kirundo Province",
    "Makamba Province",
    "Muramvya Province",
    "Muyinga Province",
    "Mwaro Province",
    "Ngozi Province",
    "Rumonge Province",
    "Rutana Province",
    "Ruyigi Province",
  ],
  BJ: [
    "Alibori Department",
    "Atakora Department",
    "Atlantique Department",
    "Borgou Department",
    "Collines Department",
    "Donga Department",
    "Kouffo Department",
    "Littoral Department",
    "Mono Department",
    "Ouémé Department",
    "Plateau Department",
    "Zou Department",
  ],
  BL: [
  ],
  BM: [
    "Devonshire Parish",
    "Hamilton Municipality",
    "Hamilton Parish",
    "Paget Parish",
    "Pembroke Parish",
    "Saint George's Municipality",
    "Saint George's Parish",
    "Sandys Parish",
    "Smith's Parish,",
    "Southampton Parish",
    "Warwick Parish",
  ],
  BN: [
    "Belait District",
    "Brunei-Muara District",
    "Temburong District",
    "Tutong District",
  ],
  BO: [
    "Beni Department",
    "Chuquisaca Department",
    "Cochabamba Department",
    "La Paz Department",
    "Oruro Department",
    "Pando Department",
    "Potosí Department",
    "Santa Cruz Department",
    "Tarija Department",
  ],
  BR: [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Espírito Santo",
    "Federal District",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
  ],
  BS: [
    "Acklins",
    "Acklins and Crooked Islands",
    "Berry Islands",
    "Bimini",
    "Black Point",
    "Cat Island",
    "Central Abaco",
    "Central Andros",
    "Central Eleuthera",
    "Crooked Island",
    "East Grand Bahama",
    "Exuma",
    "Freeport",
    "Fresh Creek",
    "Governor's Harbour",
    "Grand Cay",
    "Green Turtle Cay",
    "Harbour Island",
    "High Rock",
    "Hope Town",
    "Inagua",
    "Kemps Bay",
    "Long Island",
    "Mangrove Cay",
    "Marsh Harbour",
    "Mayaguana District",
    "Nichollstown and Berry Islands",
    "North Abaco",
    "North Andros",
    "North Eleuthera",
    "Ragged Island",
    "Rock Sound",
    "Rum Cay District",
    "San Salvador and Rum Cay",
    "San Salvador Island",
    "Sandy Point",
    "South Abaco",
    "South Andros",
    "South Eleuthera",
    "Spanish Wells",
    "West Grand Bahama",
  ],
  BT: [
    "Bumthang District",
    "Chukha District",
    "Dagana District",
    "Gasa District",
    "Haa District",
    "Lhuntse District",
    "Mongar District",
    "Paro District",
    "Pemagatshel District",
    "Punakha District",
    "Samdrup Jongkhar District",
    "Samtse District",
    "Sarpang District",
    "Thimphu District",
    "Trashigang District",
    "Trongsa District",
    "Tsirang District",
    "Wangdue Phodrang District",
    "Zhemgang District",
  ],
  BV: [
  ],
  BW: [
    "Central District",
    "Ghanzi District",
    "Kgalagadi District",
    "Kgatleng District",
    "Kweneng District",
    "Ngamiland",
    "North-East District",
    "North-West District",
    "South-East District",
    "Southern District",
  ],
  BY: [
    "Brest Region",
    "Gomel Region",
    "Grodno Region",
    "Minsk",
    "Minsk Region",
    "Mogilev Region",
    "Vitebsk Region",
  ],
  BZ: [
    "Belize District",
    "Cayo District",
    "Corozal District",
    "Orange Walk District",
    "Stann Creek District",
    "Toledo District",
  ],
  CA: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
  ],
  CC: [
  ],
  CD: [
    "Bandundu Province",
    "Bas-Congo province",
    "Bas-Uele",
    "Équateur",
    "Haut-Katanga Province",
    "Haut-Lomami District",
    "Haut-Uele",
    "Ituri Interim Administration",
    "Kasaï District",
    "Kasaï-Occidental",
    "Kasaï-Oriental",
    "Katanga Province",
    "Kinshasa",
    "Kwango District",
    "Kwilu District",
    "Lomami Province",
    "Mai-Ndombe Province",
    "Maniema",
    "Mongala District",
    "Nord-Ubangi District",
    "North Kivu",
    "Orientale Province",
    "Sankuru District",
    "South Kivu",
    "Sud-Ubangi",
    "Tanganyika Province",
    "Tshopo District",
    "Tshuapa District",
  ],
  CF: [
    "Bamingui-Bangoran Prefecture",
    "Bangui",
    "Basse-Kotto Prefecture",
    "Haut-Mbomou Prefecture",
    "Haute-Kotto Prefecture",
    "Kémo Prefecture",
    "Lobaye Prefecture",
    "Mambéré-Kadéï",
    "Mbomou Prefecture",
    "Nana-Grébizi Economic Prefecture",
    "Nana-Mambéré Prefecture",
    "Ombella-M'Poko Prefecture",
    "Ouaka Prefecture",
    "Ouham Prefecture",
    "Ouham-Pendé Prefecture",
    "Sangha-Mbaéré",
    "Vakaga Prefecture",
  ],
  CG: [
    "Bouenza Department",
    "Brazzaville",
    "Cuvette Department",
    "Cuvette-Ouest Department",
    "Kouilou Department",
    "Lékoumou Department",
    "Likouala Department",
    "Niari Department",
    "Plateaux Department",
    "Pointe-Noire",
    "Pool Department",
    "Sangha Department",
  ],
  CH: [
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneva",
    "Glarus",
    "Graubunden",
    "Jura",
    "Lucerne",
    "Neuchatel",
    "Nidwalden",
    "Obwalden",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "St. Gallen",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zurich",
  ],
  CI: [
    "Abidjan",
    "Agnéby",
    "Bafing Region",
    "Bas-Sassandra District",
    "Bas-Sassandra Region",
    "Comoé District",
    "Denguélé District",
    "Denguélé Region",
    "Dix-Huit Montagnes",
    "Fromager",
    "Gôh-Djiboua District",
    "Haut-Sassandra",
    "Lacs District",
    "Lacs Region",
    "Lagunes District",
    "Lagunes region",
    "Marahoué Region",
    "Montagnes District",
    "Moyen-Cavally",
    "Moyen-Comoé",
    "N'zi-Comoé",
    "Sassandra-Marahoué District",
    "Savanes Region",
    "Sud-Bandama",
    "Sud-Comoé",
    "Vallée du Bandama District",
    "Vallée du Bandama Region",
    "Woroba District",
    "Worodougou",
    "Yamoussoukro",
    "Zanzan Region",
  ],
  CK: [
  ],
  CL: [
    "Antofagasta Region",
    "Araucanía Region",
    "Arica y Parinacota Region",
    "Atacama Region",
    "Aysén Region",
    "Bío Bío Region",
    "Coquimbo Region",
    "Los Lagos Region",
    "Los Ríos Region",
    "Magellan and the Chilean Antarctic Region",
    "Maule Region",
    "Ñuble Region",
    "O'Higgins",
    "Santiago Metropolitan Region",
    "Tarapacá Region",
    "Valparaíso",
  ],
  CM: [
    "Adamawa",
    "Centre",
    "East",
    "Far North",
    "Littoral",
    "North",
    "Northwest",
    "South",
    "Southwest",
    "West",
  ],
  CN: [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hong Kong",
    "Hubei",
    "Hunan",
    "Inner Mongolia",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Macau",
    "Ningxia",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Tianjin",
    "Tibet",
    "Xinjiang",
    "Yunnan",
    "Zhejiang",
  ],
  CO: [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlantico",
    "Bogota D.C.",
    "Bolivar",
    "Boyaca",
    "Caldas",
    "Caqueta",
    "Casanare",
    "Cauca",
    "Cesar",
    "Choco",
    "Cordoba",
    "Cundinamarca",
    "Guainia",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Narino",
    "Norte de Santander",
    "Putumayo",
    "Quindio",
    "Risaralda",
    "San Andres y Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupes",
    "Vichada",
  ],
  CR: [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limon",
    "Puntarenas",
    "San Jose",
  ],
  CU: [
    "Artemisa",
    "Camaguey",
    "Ciego de Avila",
    "Cienfuegos",
    "Granma",
    "Guantanamo",
    "Holguin",
    "Isla de la Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Mayabeque",
    "Pinar del Rio",
    "Sancti Spiritus",
    "Santiago de Cuba",
    "Villa Clara",
  ],
  CV: [
    "Barlavento Islands",
    "Boa Vista",
    "Brava",
    "Maio Municipality",
    "Mosteiros",
    "Paul",
    "Porto Novo",
    "Praia",
    "Ribeira Brava Municipality",
    "Ribeira Grande",
    "Ribeira Grande de Santiago",
    "Sal",
    "Santa Catarina",
    "Santa Catarina do Fogo",
    "Santa Cruz",
    "São Domingos",
    "São Filipe",
    "São Lourenço dos Órgãos",
    "São Miguel",
    "São Vicente",
    "Sotavento Islands",
    "Tarrafal",
    "Tarrafal de São Nicolau",
  ],
  CX: [
  ],
  CY: [
    "Famagusta District",
    "Kyrenia District",
    "Larnaca District",
    "Limassol District",
    "Nicosia District",
    "Paphos District",
  ],
  CZ: [
    "Central Bohemian",
    "Hradec Kralove",
    "Karlovy Vary",
    "Liberec",
    "Moravian-Silesian",
    "Olomouc",
    "Pardubice",
    "Plzen",
    "Prague",
    "South Bohemian",
    "South Moravian",
    "Usti nad Labem",
    "Vysocina",
    "Zlin",
  ],
  DE: [
    "Baden-Wurttemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
  ],
  DJ: [
    "Ali Sabieh Region",
    "Arta Region",
    "Dikhil Region",
    "Djibouti",
    "Obock Region",
    "Tadjourah Region",
  ],
  DK: [
    "Capital Region",
    "Central Denmark",
    "North Denmark",
    "Region Zealand",
    "Southern Denmark",
  ],
  DM: [
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint John Parish",
    "Saint Joseph Parish",
    "Saint Luke Parish",
    "Saint Mark Parish",
    "Saint Patrick Parish",
    "Saint Paul Parish",
    "Saint Peter Parish",
  ],
  DO: [
    "Azua",
    "Bahoruco",
    "Barahona",
    "Dajabon",
    "Distrito Nacional",
    "Duarte",
    "El Seibo",
    "Elias Pina",
    "Espaillat",
    "Hato Mayor",
    "Hermanas Mirabal",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "Maria Trinidad Sanchez",
    "Monsenor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Samana",
    "San Cristobal",
    "San Jose de Ocoa",
    "San Juan",
    "San Pedro de Macoris",
    "Sanchez Ramirez",
    "Santiago",
    "Santiago Rodriguez",
    "Santo Domingo",
    "Valverde",
  ],
  DZ: [
    "Adrar Province",
    "Aïn Defla Province",
    "Aïn Témouchent Province",
    "Algiers Province",
    "Annaba Province",
    "Batna Province",
    "Béchar Province",
    "Béjaïa Province",
    "Biskra",
    "Blida Province",
    "Bordj Bou Arréridj Province",
    "Bouïra Province",
    "Boumerdès Province",
    "Chlef Province",
    "Constantine Province",
    "Djelfa Province",
    "El Bayadh Province",
    "El Oued Province",
    "El Tarf Province",
    "Ghardaïa Province",
    "Guelma Province",
    "Illizi Province",
    "Jijel Province",
    "Khenchela Province",
    "Laghouat Province",
    "M'Sila Province",
    "Mascara Province",
    "Médéa Province",
    "Mila Province",
    "Mostaganem Province",
    "Naama Province",
    "Oran Province",
    "Ouargla Province",
    "Oum El Bouaghi Province",
    "Relizane Province",
    "Saïda Province",
    "Sétif Province",
    "Skikda Province",
    "Souk Ahras Province",
    "Tamanghasset Province",
    "Tébessa Province",
    "Tiaret Province",
    "Tindouf Province",
    "Tipasa Province",
    "Tissemsilt Province",
    "Tizi Ouzou Province",
    "Tlemcen Province",
  ],
  EC: [
    "Azuay",
    "Bolivar",
    "Canar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galapagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Rios",
    "Manabi",
    "Morona Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsachilas",
    "Sucumbios",
    "Tungurahua",
    "Zamora Chinchipe",
  ],
  EE: [
    "Harju County",
    "Hiiu County",
    "Ida-Viru County",
    "Järva County",
    "Jõgeva County",
    "Lääne County",
    "Lääne-Viru County",
    "Pärnu County",
    "Põlva County",
    "Rapla County",
    "Saare County",
    "Tartu County",
    "Valga County",
    "Viljandi County",
    "Võru County",
  ],
  EG: [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
  ],
  EH: [
  ],
  ER: [
    "Anseba Region",
    "Debub Region",
    "Gash-Barka Region",
    "Maekel Region",
    "Northern Red Sea Region",
    "Southern Red Sea Region",
  ],
  ES: [
    "Andalucia",
    "Aragon",
    "Asturias",
    "Baleares",
    "Canarias",
    "Cantabria",
    "Castilla y Leon",
    "Castilla-La Mancha",
    "Cataluna",
    "Ceuta",
    "Comunidad Valenciana",
    "Extremadura",
    "Galicia",
    "La Rioja",
    "Madrid",
    "Melilla",
    "Murcia",
    "Navarra",
    "Pais Vasco",
  ],
  ET: [
    "Addis Ababa",
    "Afar Region",
    "Amhara Region",
    "Benishangul-Gumuz Region",
    "Dire Dawa",
    "Gambela Region",
    "Harari Region",
    "Oromia Region",
    "Somali Region",
    "Southern Nations, Nationalities, and Peoples' Region",
    "Tigray Region",
  ],
  FI: [
    "Åland Islands",
    "Central Finland",
    "Central Ostrobothnia",
    "Eastern Finland Province",
    "Finland Proper",
    "Kainuu",
    "Kymenlaakso",
    "Lapland",
    "North Karelia",
    "Northern Ostrobothnia",
    "Northern Savonia",
    "Ostrobothnia",
    "Oulu Province",
    "Päijänne Tavastia",
    "Pirkanmaa",
    "Satakunta",
    "South Karelia",
    "Southern Ostrobothnia",
    "Southern Savonia",
    "Tavastia Proper",
    "Uusimaa",
  ],
  FJ: [
    "Ba",
    "Bua",
    "Cakaudrove",
    "Central Division",
    "Eastern Division",
    "Kadavu",
    "Lau",
    "Lomaiviti",
    "Macuata",
    "Nadroga-Navosa",
    "Naitasiri",
    "Namosi",
    "Northern Division",
    "Ra",
    "Rewa",
    "Rotuma",
    "Serua",
    "Tailevu",
    "Western Division",
  ],
  FK: [
  ],
  FM: [
    "Chuuk State",
    "Kosrae State",
    "Pohnpei State",
    "Yap State",
  ],
  FO: [
  ],
  FR: [
    "Auvergne-Rhone-Alpes",
    "Bourgogne-Franche-Comte",
    "Bretagne",
    "Centre-Val de Loire",
    "Corse",
    "Grand Est",
    "Guadeloupe",
    "Guyane",
    "Hauts-de-France",
    "Ile-de-France",
    "La Reunion",
    "Martinique",
    "Mayotte",
    "Normandie",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Cote d Azur",
  ],
  GA: [
    "Estuaire Province",
    "Haut-Ogooué Province",
    "Moyen-Ogooué Province",
    "Ngounié Province",
    "Nyanga Province",
    "Ogooué-Ivindo Province",
    "Ogooué-Lolo Province",
    "Ogooué-Maritime Province",
    "Woleu-Ntem Province",
  ],
  GB: [
    "England",
    "Northern Ireland",
    "Scotland",
    "Wales",
  ],
  GD: [
    "Carriacou and Petite Martinique",
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint John Parish",
    "Saint Mark Parish",
    "Saint Patrick Parish",
  ],
  GE: [
    "Adjara",
    "Autonomous Republic of Abkhazia",
    "Guria",
    "Imereti",
    "Kakheti",
    "Khelvachauri Municipality",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Javakheti",
    "Senaki Municipality",
    "Shida Kartli",
    "Tbilisi",
  ],
  GG: [
  ],
  GH: [
    "Ashanti Region",
    "Brong-Ahafo Region",
    "Central Region",
    "Eastern Region",
    "Greater Accra Region",
    "Northern Region",
    "Upper East Region",
    "Upper West Region",
    "Volta Region",
    "Western Region",
  ],
  GI: [
  ],
  GL: [
  ],
  GM: [
    "Banjul",
    "Central River Division",
    "Lower River Division",
    "North Bank Division",
    "Upper River Division",
    "West Coast Division",
  ],
  GN: [
    "Beyla Prefecture",
    "Boffa Prefecture",
    "Boké Prefecture",
    "Boké Region",
    "Conakry",
    "Coyah Prefecture",
    "Dabola Prefecture",
    "Dalaba Prefecture",
    "Dinguiraye Prefecture",
    "Dubréka Prefecture",
    "Faranah Prefecture",
    "Forécariah Prefecture",
    "Fria Prefecture",
    "Gaoual Prefecture",
    "Guéckédou Prefecture",
    "Kankan Prefecture",
    "Kankan Region",
    "Kérouané Prefecture",
    "Kindia Prefecture",
    "Kindia Region",
    "Kissidougou Prefecture",
    "Koubia Prefecture",
    "Koundara Prefecture",
    "Kouroussa Prefecture",
    "Labé Prefecture",
    "Labé Region",
    "Lélouma Prefecture",
    "Lola Prefecture",
    "Macenta Prefecture",
    "Mali Prefecture",
    "Mamou Prefecture",
    "Mamou Region",
    "Mandiana Prefecture",
    "Nzérékoré Prefecture",
    "Nzérékoré Region",
    "Pita Prefecture",
    "Siguiri Prefecture",
    "Télimélé Prefecture",
    "Tougué Prefecture",
    "Yomou Prefecture",
  ],
  GP: [
  ],
  GQ: [
    "Annobón Province",
    "Bioko Norte Province",
    "Bioko Sur Province",
    "Centro Sur Province",
    "Insular Region",
    "Kié-Ntem Province",
    "Litoral Province",
    "Río Muni",
    "Wele-Nzas Province",
  ],
  GR: [
    "Attica",
    "Central Greece",
    "Central Macedonia",
    "Crete",
    "Eastern Macedonia and Thrace",
    "Epirus",
    "Ionian Islands",
    "North Aegean",
    "Peloponnese",
    "South Aegean",
    "Thessaly",
    "Western Greece",
    "Western Macedonia",
  ],
  GS: [
  ],
  GT: [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Peten",
    "Quetzaltenango",
    "Quiche",
    "Retalhuleu",
    "Sacatepequez",
    "San Marcos",
    "Santa Rosa",
    "Solola",
    "Suchitepequez",
    "Totonicapan",
    "Zacapa",
  ],
  GU: [
  ],
  GW: [
    "Bafatá",
    "Biombo Region",
    "Bolama Region",
    "Cacheu Region",
    "Gabú Region",
    "Leste Province",
    "Norte Province",
    "Oio Region",
    "Quinara Region",
    "Sul Province",
    "Tombali Region",
  ],
  GY: [
    "Barima-Waini",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "East Berbice-Corentyne",
    "Essequibo Islands-West Demerara",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni",
    "Upper Demerara-Berbice",
    "Upper Takutu-Upper Essequibo",
  ],
  HK: [
    "Hong Kong Island",
    "Kowloon",
    "New Territories",
  ],
  HM: [
  ],
  HN: [
    "Atlantida",
    "Choluteca",
    "Colon",
    "Comayagua",
    "Copan",
    "Cortes",
    "El Paraiso",
    "Francisco Morazan",
    "Gracias a Dios",
    "Intibuca",
    "Islas de la Bahia",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Barbara",
    "Valle",
    "Yoro",
  ],
  HR: [
    "Bjelovar-Bilogora County",
    "Brod-Posavina County",
    "Dubrovnik-Neretva County",
    "Istria County",
    "Koprivnica-Križevci County",
    "Krapina-Zagorje County",
    "Lika-Senj County",
    "Međimurje County",
    "Osijek-Baranja County",
    "Požega-Slavonia County",
    "Primorje-Gorski Kotar County",
    "Šibenik-Knin County",
    "Sisak-Moslavina County",
    "Split-Dalmatia County",
    "Varaždin County",
    "Virovitica-Podravina County",
    "Vukovar-Syrmia County",
    "Zadar County",
    "Zagreb",
    "Zagreb County",
  ],
  HT: [
    "Artibonite",
    "Centre",
    "Grand'Anse",
    "Nippes",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est",
  ],
  HU: [
    "Bacs-Kiskun",
    "Baranya",
    "Bekes",
    "Borsod-Abauj-Zemplen",
    "Budapest",
    "Csongrad-Csanad",
    "Fejer",
    "Gyor-Moson-Sopron",
    "Hajdu-Bihar",
    "Heves",
    "Jasz-Nagykun-Szolnok",
    "Komarom-Esztergom",
    "Nograd",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmar-Bereg",
    "Tolna",
    "Vas",
    "Veszprem",
    "Zala",
  ],
  ID: [
    "Aceh",
    "Bali",
    "Banten",
    "Central Java",
    "Central Kalimantan",
    "Central Sulawesi",
    "East Java",
    "East Kalimantan",
    "East Nusa Tenggara",
    "Jakarta",
    "Jambi",
    "Lampung",
    "North Sumatra",
    "Papua",
    "Riau",
    "South Sulawesi",
    "South Sumatra",
    "West Java",
    "West Kalimantan",
    "West Nusa Tenggara",
    "West Sumatra",
    "Yogyakarta",
  ],
  IE: [
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
  ],
  IL: [
    "Central District",
    "Haifa District",
    "Jerusalem District",
    "Northern District",
    "Southern District",
    "Tel Aviv District",
  ],
  IM: [
  ],
  IN: [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
  IO: [
  ],
  IQ: [
    "Al Anbar Governorate",
    "Al Muthanna Governorate",
    "Al-Qādisiyyah Governorate",
    "Babylon Governorate",
    "Baghdad Governorate",
    "Basra Governorate",
    "Dhi Qar Governorate",
    "Diyala Governorate",
    "Dohuk Governorate",
    "Erbil Governorate",
    "Karbala Governorate",
    "Kirkuk Governorate",
    "Maysan Governorate",
    "Najaf Governorate",
    "Nineveh Governorate",
    "Saladin Governorate",
    "Sulaymaniyah Governorate",
    "Wasit Governorate",
  ],
  IR: [
    "Alborz Province",
    "Ardabil Province",
    "Bushehr Province",
    "Chaharmahal and Bakhtiari Province",
    "East Azerbaijan Province",
    "Fars Province",
    "Gilan Province",
    "Golestan Province",
    "Hormozgan Province",
    "Ilam Province",
    "Isfahan Province",
    "Kerman Province",
    "Kermanshah Province",
    "Khuzestan Province",
    "Kohgiluyeh and Boyer-Ahmad Province",
    "Kurdistan Province",
    "Lorestan Province",
    "Markazi Province",
    "Mazandaran Province",
    "North Khorasan Province",
    "Qazvin Province",
    "Qom Province",
    "Razavi Khorasan Province",
    "Semnan Province",
    "Sistan and Baluchestan",
    "South Khorasan Province",
    "Tehran Province",
    "West Azarbaijan Province",
    "Yazd Province",
    "Zanjan Province",
  ],
  IS: [
    "Capital Region",
    "Eastern Region",
    "Northeastern Region",
    "Northwestern Region",
    "Southern Peninsula Region",
    "Southern Region",
    "Western Region",
    "Westfjords",
  ],
  IT: [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino-Alto Adige",
    "Umbria",
    "Valle d Aosta",
    "Veneto",
  ],
  JE: [
  ],
  JM: [
    "Clarendon Parish",
    "Hanover Parish",
    "Kingston Parish",
    "Manchester Parish",
    "Portland Parish",
    "Saint Andrew",
    "Saint Ann Parish",
    "Saint Catherine Parish",
    "Saint Elizabeth Parish",
    "Saint James Parish",
    "Saint Mary Parish",
    "Saint Thomas Parish",
    "Trelawny Parish",
    "Westmoreland Parish",
  ],
  JO: [
    "Ajloun Governorate",
    "Amman Governorate",
    "Aqaba Governorate",
    "Balqa Governorate",
    "Irbid Governorate",
    "Jerash Governorate",
    "Karak Governorate",
    "Ma'an Governorate",
    "Madaba Governorate",
    "Mafraq Governorate",
    "Tafilah Governorate",
    "Zarqa Governorate",
  ],
  JP: [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
  ],
  KE: [
    "Baringo County",
    "Bomet County",
    "Bungoma County",
    "Busia County",
    "Central Province",
    "Coast Province",
    "Eastern Province",
    "Elgeyo-Marakwet County",
    "Embu County",
    "Garissa County",
    "Homa Bay County",
    "Isiolo County",
    "Kajiado County",
    "Kakamega County",
    "Kericho County",
    "Kiambu County",
    "Kilifi County",
    "Kirinyaga County",
    "Kisii County",
    "Kisumu County",
    "Kitui County",
    "Kwale County",
    "Laikipia County",
    "Lamu County",
    "Machakos County",
    "Makueni County",
    "Mandera County",
    "Marsabit County",
    "Meru County",
    "Migori County",
    "Mombasa County",
    "Muranga County",
    "Nairobi",
    "Nakuru District",
    "Nandi District",
    "Narok County",
    "North Eastern Province",
    "Nyamira District",
    "Nyandarua County",
    "Nyanza Province",
    "Nyeri County",
    "Rift Valley Province",
    "Samburu County",
    "Siaya County",
    "Taita–Taveta County",
    "Tana River County",
    "Tharaka Nithi County",
    "Trans-Nzoia District",
    "Turkana County",
    "Uasin Gishu District",
    "Vihiga District",
    "Wajir County",
    "West Pokot County",
    "Western Province",
  ],
  KG: [
    "Batken Region",
    "Bishkek",
    "Chuy Region",
    "Issyk-Kul Region",
    "Jalal-Abad Region",
    "Naryn Region",
    "Osh",
    "Osh Region",
    "Talas Region",
  ],
  KH: [
    "Banteay Meanchey Province",
    "Battambang Province",
    "Kampong Cham Province",
    "Kampong Chhnang Province",
    "Kampong Speu Province",
    "Kampot Province",
    "Kandal Province",
    "Kep Province",
    "Koh Kong Province",
    "Kratié Province",
    "Mondulkiri Province",
    "Oddar Meanchey Province",
    "Pailin Province",
    "Phnom Penh",
    "Preah Vihear Province",
    "Prey Veng Province",
    "Pursat Province",
    "Ratanakiri Province",
    "Siem Reap Province",
    "Sihanoukville Province",
    "Stung Treng Province",
    "Svay Rieng Province",
    "Takéo Province",
  ],
  KI: [
    "Gilbert Islands",
    "Line Islands",
    "Phoenix Islands",
  ],
  KM: [
    "Anjouan",
    "Grande Comore",
    "Mohéli",
  ],
  KN: [
    "Christ Church Nichola Town Parish",
    "Nevis",
    "Saint Anne Sandy Point Parish",
    "Saint George Gingerland Parish",
    "Saint James Windward Parish",
    "Saint John Capisterre Parish",
    "Saint John Figtree Parish",
    "Saint Kitts",
    "Saint Mary Cayon Parish",
    "Saint Paul Capisterre Parish",
    "Saint Paul Charlestown Parish",
    "Saint Peter Basseterre Parish",
    "Saint Thomas Lowland Parish",
    "Saint Thomas Middle Island Parish",
    "Trinity Palmetto Point Parish",
  ],
  KP: [
    "Chagang Province",
    "Kangwon Province",
    "North Hamgyong Province",
    "North Hwanghae Province",
    "North Pyongan Province",
    "Pyongyang",
    "Rason",
    "Ryanggang Province",
    "South Hamgyong Province",
    "South Hwanghae Province",
    "South Pyongan Province",
  ],
  KR: [
    "Busan",
    "Daegu",
    "Daejeon",
    "Gangwon",
    "Gwangju",
    "Gyeonggi",
    "Incheon",
    "Jeju",
    "North Chungcheong",
    "North Gyeongsang",
    "North Jeolla",
    "Sejong",
    "Seoul",
    "South Chungcheong",
    "South Gyeongsang",
    "South Jeolla",
    "Ulsan",
  ],
  KW: [
    "Al Ahmadi Governorate",
    "Al Farwaniyah Governorate",
    "Al Jahra Governorate",
    "Capital Governorate",
    "Hawalli Governorate",
    "Mubarak Al-Kabeer Governorate",
  ],
  KY: [
  ],
  KZ: [
    "Akmola Region",
    "Aktobe Region",
    "Almaty",
    "Almaty Region",
    "Atyrau Region",
    "Baikonur",
    "East Kazakhstan Region",
    "Jambyl Region",
    "Karaganda Region",
    "Kostanay Region",
    "Kyzylorda Region",
    "Mangystau Region",
    "North Kazakhstan Region",
    "Nur-Sultan",
    "Pavlodar Region",
    "Turkestan Region",
    "West Kazakhstan Province",
  ],
  LA: [
    "Attapeu Province",
    "Bokeo Province",
    "Bolikhamsai Province",
    "Champasak Province",
    "Houaphanh Province",
    "Khammouane Province",
    "Luang Namtha Province",
    "Luang Prabang Province",
    "Oudomxay Province",
    "Phongsaly Province",
    "Sainyabuli Province",
    "Salavan Province",
    "Savannakhet Province",
    "Sekong Province",
    "Vientiane Prefecture",
    "Vientiane Province",
    "Xaisomboun",
    "Xaisomboun Province",
    "Xiangkhouang Province",
  ],
  LB: [
    "Akkar Governorate",
    "Baalbek-Hermel Governorate",
    "Beirut Governorate",
    "Beqaa Governorate",
    "Mount Lebanon Governorate",
    "Nabatieh Governorate",
    "North Governorate",
    "South Governorate",
  ],
  LC: [
    "Anse la Raye Quarter",
    "Canaries",
    "Castries Quarter",
    "Choiseul Quarter",
    "Dauphin Quarter",
    "Dennery Quarter",
    "Gros Islet Quarter",
    "Laborie Quarter",
    "Micoud Quarter",
    "Praslin Quarter",
    "Soufrière Quarter",
    "Vieux Fort Quarter",
  ],
  LI: [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz",
  ],
  LK: [
    "Ampara District",
    "Anuradhapura District",
    "Badulla District",
    "Batticaloa District",
    "Central Province",
    "Colombo District",
    "Eastern Province",
    "Galle District",
    "Gampaha District",
    "Hambantota District",
    "Jaffna District",
    "Kalutara District",
    "Kandy District",
    "Kegalle District",
    "Kilinochchi District",
    "Mannar District",
    "Matale District",
    "Matara District",
    "Monaragala District",
    "Mullaitivu District",
    "North Central Province",
    "North Western Province",
    "Northern Province",
    "Nuwara Eliya District",
    "Polonnaruwa District",
    "Puttalam District",
    "Ratnapura district",
    "Sabaragamuwa Province",
    "Southern Province",
    "Trincomalee District",
    "Uva Province",
    "Vavuniya District",
    "Western Province",
  ],
  LR: [
    "Bomi County",
    "Bong County",
    "Gbarpolu County",
    "Grand Bassa County",
    "Grand Cape Mount County",
    "Grand Gedeh County",
    "Grand Kru County",
    "Lofa County",
    "Margibi County",
    "Maryland County",
    "Montserrado County",
    "Nimba",
    "River Cess County",
    "River Gee County",
    "Sinoe County",
  ],
  LS: [
    "Berea District",
    "Butha-Buthe District",
    "Leribe District",
    "Mafeteng District",
    "Maseru District",
    "Mohale's Hoek District",
    "Mokhotlong District",
    "Qacha's Nek District",
    "Quthing District",
    "Thaba-Tseka District",
  ],
  LT: [
    "Akmenė District Municipality",
    "Alytus City Municipality",
    "Alytus County",
    "Alytus District Municipality",
    "Birštonas Municipality",
    "Biržai District Municipality",
    "Druskininkai municipality",
    "Elektrėnai municipality",
    "Ignalina District Municipality",
    "Jonava District Municipality",
    "Joniškis District Municipality",
    "Jurbarkas District Municipality",
    "Kaišiadorys District Municipality",
    "Kalvarija municipality",
    "Kaunas City Municipality",
    "Kaunas County",
    "Kaunas District Municipality",
    "Kazlų Rūda municipality",
    "Kėdainiai District Municipality",
    "Kelmė District Municipality",
    "Klaipeda City Municipality",
    "Klaipėda County",
    "Klaipėda District Municipality",
    "Kretinga District Municipality",
    "Kupiškis District Municipality",
    "Lazdijai District Municipality",
    "Marijampolė County",
    "Marijampolė Municipality",
    "Mažeikiai District Municipality",
    "Molėtai District Municipality",
    "Neringa Municipality",
    "Pagėgiai municipality",
    "Pakruojis District Municipality",
    "Palanga City Municipality",
    "Panevėžys City Municipality",
    "Panevėžys County",
    "Panevėžys District Municipality",
    "Pasvalys District Municipality",
    "Plungė District Municipality",
    "Prienai District Municipality",
    "Radviliškis District Municipality",
    "Raseiniai District Municipality",
    "Rietavas municipality",
    "Rokiškis District Municipality",
    "Šakiai District Municipality",
    "Šalčininkai District Municipality",
    "Šiauliai City Municipality",
    "Šiauliai County",
    "Šiauliai District Municipality",
    "Šilalė District Municipality",
    "Šilutė District Municipality",
    "Širvintos District Municipality",
    "Skuodas District Municipality",
    "Švenčionys District Municipality",
    "Tauragė County",
    "Tauragė District Municipality",
    "Telšiai County",
    "Telšiai District Municipality",
    "Trakai District Municipality",
    "Ukmergė District Municipality",
    "Utena County",
    "Utena District Municipality",
    "Varėna District Municipality",
    "Vilkaviškis District Municipality",
    "Vilnius City Municipality",
    "Vilnius County",
    "Vilnius District Municipality",
    "Visaginas Municipality",
    "Zarasai District Municipality",
  ],
  LU: [
    "Canton of Capellen",
    "Canton of Clervaux",
    "Canton of Diekirch",
    "Canton of Echternach",
    "Canton of Esch-sur-Alzette",
    "Canton of Grevenmacher",
    "Canton of Luxembourg",
    "Canton of Mersch",
    "Canton of Redange",
    "Canton of Remich",
    "Canton of Vianden",
    "Canton of Wiltz",
    "Diekirch District",
    "Grevenmacher District",
    "Luxembourg District",
  ],
  LV: [
    "Aglona Municipality",
    "Aizkraukle Municipality",
    "Aizpute Municipality",
    "Aknīste Municipality",
    "Aloja Municipality",
    "Alsunga Municipality",
    "Alūksne Municipality",
    "Amata Municipality",
    "Ape Municipality",
    "Auce Municipality",
    "Babīte Municipality",
    "Baldone Municipality",
    "Baltinava Municipality",
    "Balvi Municipality",
    "Bauska Municipality",
    "Beverīna Municipality",
    "Brocēni Municipality",
    "Burtnieki Municipality",
    "Carnikava Municipality",
    "Cēsis Municipality",
    "Cesvaine Municipality",
    "Cibla Municipality",
    "Dagda Municipality",
    "Daugavpils",
    "Daugavpils Municipality",
    "Dobele Municipality",
    "Dundaga Municipality",
    "Durbe Municipality",
    "Engure Municipality",
    "Ērgļi Municipality",
    "Garkalne Municipality",
    "Grobiņa Municipality",
    "Gulbene Municipality",
    "Iecava Municipality",
    "Ikšķile Municipality",
    "Ilūkste Municipality",
    "Inčukalns Municipality",
    "Jaunjelgava Municipality",
    "Jaunpiebalga Municipality",
    "Jaunpils Municipality",
    "Jēkabpils",
    "Jēkabpils Municipality",
    "Jelgava",
    "Jelgava Municipality",
    "Jūrmala",
    "Kandava Municipality",
    "Kārsava Municipality",
    "Ķegums Municipality",
    "Ķekava Municipality",
    "Kocēni Municipality",
    "Koknese Municipality",
    "Krāslava Municipality",
    "Krimulda Municipality",
    "Krustpils Municipality",
    "Kuldīga Municipality",
    "Lielvārde Municipality",
    "Liepāja",
    "Līgatne Municipality",
    "Limbaži Municipality",
    "Līvāni Municipality",
    "Lubāna Municipality",
    "Ludza Municipality",
    "Madona Municipality",
    "Mālpils Municipality",
    "Mārupe Municipality",
    "Mazsalaca Municipality",
    "Mērsrags Municipality",
    "Naukšēni Municipality",
    "Nereta Municipality",
    "Nīca Municipality",
    "Ogre Municipality",
    "Olaine Municipality",
    "Ozolnieki Municipality",
    "Pārgauja Municipality",
    "Pāvilosta Municipality",
    "Pļaviņas Municipality",
    "Preiļi Municipality",
    "Priekule Municipality",
    "Priekuļi Municipality",
    "Rauna Municipality",
    "Rēzekne",
    "Rēzekne Municipality",
    "Riebiņi Municipality",
    "Riga",
    "Roja Municipality",
    "Ropaži Municipality",
    "Rucava Municipality",
    "Rugāji Municipality",
    "Rūjiena Municipality",
    "Rundāle Municipality",
    "Sala Municipality",
    "Salacgrīva Municipality",
    "Salaspils Municipality",
    "Saldus Municipality",
    "Saulkrasti Municipality",
    "Sēja Municipality",
    "Sigulda Municipality",
    "Skrīveri Municipality",
    "Skrunda Municipality",
    "Smiltene Municipality",
    "Stopiņi Municipality",
    "Strenči Municipality",
    "Talsi Municipality",
    "Tērvete Municipality",
    "Tukums Municipality",
    "Vaiņode Municipality",
    "Valka Municipality",
    "Valmiera",
    "Varakļāni Municipality",
    "Vārkava Municipality",
    "Vecpiebalga Municipality",
    "Vecumnieki Municipality",
    "Ventspils",
    "Ventspils Municipality",
    "Viesīte Municipality",
    "Viļaka Municipality",
    "Viļāni Municipality",
    "Zilupe Municipality",
  ],
  LY: [
    "Al Wahat District",
    "Benghazi",
    "Derna District",
    "Ghat District",
    "Jabal al Akhdar",
    "Jabal al Gharbi District",
    "Jafara",
    "Jufra",
    "Kufra District",
    "Marj District",
    "Misrata District",
    "Murqub",
    "Murzuq District",
    "Nalut District",
    "Nuqat al Khams",
    "Sabha District",
    "Sirte District",
    "Tripoli District",
    "Wadi al Hayaa District",
    "Wadi al Shatii District",
    "Zawiya District",
  ],
  MA: [
    "Beni Mellal-Khenifra",
    "Casablanca-Settat",
    "Dakhla-Oued Ed-Dahab",
    "Draa-Tafilalet",
    "Fes-Meknes",
    "Guelmim-Oued Noun",
    "Laayoune-Sakia El Hamra",
    "Marrakesh-Safi",
    "Oriental",
    "Rabat-Sale-Kenitra",
    "Souss-Massa",
    "Tanger-Tetouan-Al Hoceima",
  ],
  MC: [
  ],
  MD: [
    "Anenii Noi District",
    "Bălți Municipality",
    "Basarabeasca District",
    "Bender Municipality",
    "Briceni District",
    "Cahul District",
    "Călărași District",
    "Cantemir District",
    "Căușeni District",
    "Chișinău Municipality",
    "Cimișlia District",
    "Criuleni District",
    "Dondușeni District",
    "Drochia District",
    "Dubăsari District",
    "Edineț District",
    "Fălești District",
    "Florești District",
    "Gagauzia",
    "Glodeni District",
    "Hîncești District",
    "Ialoveni District",
    "Nisporeni District",
    "Ocnița District",
    "Orhei District",
    "Rezina District",
    "Rîșcani District",
    "Sîngerei District",
    "Șoldănești District",
    "Soroca District",
    "Ștefan Vodă District",
    "Strășeni District",
    "Taraclia District",
    "Telenești District",
    "Transnistria autonomous territorial unit",
    "Ungheni District",
  ],
  ME: [
    "Andrijevica Municipality",
    "Bar Municipality",
    "Berane Municipality",
    "Bijelo Polje Municipality",
    "Budva Municipality",
    "Danilovgrad Municipality",
    "Gusinje Municipality",
    "Kolašin Municipality",
    "Kotor Municipality",
    "Mojkovac Municipality",
    "Nikšić Municipality",
    "Old Royal Capital Cetinje",
    "Petnjica Municipality",
    "Plav Municipality",
    "Pljevlja Municipality",
    "Plužine Municipality",
    "Podgorica Municipality",
    "Rožaje Municipality",
    "Šavnik Municipality",
    "Tivat Municipality",
    "Ulcinj Municipality",
    "Žabljak Municipality",
  ],
  MF: [
  ],
  MG: [
    "Antananarivo Province",
    "Antsiranana Province",
    "Fianarantsoa Province",
    "Mahajanga Province",
    "Toamasina Province",
    "Toliara Province",
  ],
  MH: [
    "Ralik Chain",
    "Ratak Chain",
  ],
  MK: [
    "Aerodrom Municipality",
    "Aračinovo Municipality",
    "Berovo Municipality",
    "Bitola Municipality",
    "Bogdanci Municipality",
    "Bogovinje Municipality",
    "Bosilovo Municipality",
    "Brvenica Municipality",
    "Butel Municipality",
    "Čair Municipality",
    "Čaška Municipality",
    "Centar Municipality",
    "Centar Župa Municipality",
    "Češinovo-Obleševo Municipality",
    "Čučer-Sandevo Municipality",
    "Debarca Municipality",
    "Delčevo Municipality",
    "Demir Hisar Municipality",
    "Demir Kapija Municipality",
    "Dojran Municipality",
    "Dolneni Municipality",
    "Drugovo Municipality",
    "Gazi Baba Municipality",
    "Gevgelija Municipality",
    "Gjorče Petrov Municipality",
    "Gostivar Municipality",
    "Gradsko Municipality",
    "Greater Skopje",
    "Ilinden Municipality",
    "Jegunovce Municipality",
    "Karbinci",
    "Karpoš Municipality",
    "Kavadarci Municipality",
    "Kičevo Municipality",
    "Kisela Voda Municipality",
    "Kočani Municipality",
    "Konče Municipality",
    "Kratovo Municipality",
    "Kriva Palanka Municipality",
    "Krivogaštani Municipality",
    "Kruševo Municipality",
    "Kumanovo Municipality",
    "Lipkovo Municipality",
    "Lozovo Municipality",
    "Makedonska Kamenica Municipality",
    "Makedonski Brod Municipality",
    "Mavrovo and Rostuša Municipality",
    "Mogila Municipality",
    "Negotino Municipality",
    "Novaci Municipality",
    "Novo Selo Municipality",
    "Ohrid Municipality",
    "Oslomej Municipality",
    "Pehčevo Municipality",
    "Petrovec Municipality",
    "Plasnica Municipality",
    "Prilep Municipality",
    "Probištip Municipality",
    "Radoviš Municipality",
    "Rankovce Municipality",
    "Resen Municipality",
    "Rosoman Municipality",
    "Saraj Municipality",
    "Sopište Municipality",
    "Staro Nagoričane Municipality",
    "Štip Municipality",
    "Struga Municipality",
    "Strumica Municipality",
    "Studeničani Municipality",
    "Šuto Orizari Municipality",
    "Sveti Nikole Municipality",
    "Tearce Municipality",
    "Tetovo Municipality",
    "Valandovo Municipality",
    "Vasilevo Municipality",
    "Veles Municipality",
    "Vevčani Municipality",
    "Vinica Municipality",
    "Vraneštica Municipality",
    "Vrapčište Municipality",
    "Zajas Municipality",
    "Zelenikovo Municipality",
    "Želino Municipality",
    "Zrnovci Municipality",
  ],
  ML: [
    "Bamako",
    "Gao Region",
    "Kayes Region",
    "Kidal Region",
    "Koulikoro Region",
    "Ménaka Region",
    "Mopti Region",
    "Ségou Region",
    "Sikasso Region",
    "Taoudénit Region",
    "Tombouctou Region",
  ],
  MM: [
    "Ayeyarwady Region",
    "Bago",
    "Chin State",
    "Kachin State",
    "Kayah State",
    "Kayin State",
    "Magway Region",
    "Mandalay Region",
    "Mon State",
    "Naypyidaw Union Territory",
    "Rakhine State",
    "Sagaing Region",
    "Shan State",
    "Tanintharyi Region",
    "Yangon Region",
  ],
  MN: [
    "Arkhangai Province",
    "Bayan-Ölgii Province",
    "Bayankhongor Province",
    "Bulgan Province",
    "Darkhan-Uul Province",
    "Dornod Province",
    "Dornogovi Province",
    "Dundgovi Province",
    "Govi-Altai Province",
    "Govisümber Province",
    "Khentii Province",
    "Khovd Province",
    "Khövsgöl Province",
    "Ömnögovi Province",
    "Orkhon Province",
    "Övörkhangai Province",
    "Selenge Province",
    "Sükhbaatar Province",
    "Töv Province",
    "Uvs Province",
    "Zavkhan Province",
  ],
  MO: [
  ],
  MP: [
  ],
  MQ: [
  ],
  MR: [
    "Adrar Region",
    "Assaba Region",
    "Brakna Region",
    "Dakhlet Nouadhibou",
    "Gorgol Region",
    "Guidimaka Region",
    "Hodh Ech Chargui Region",
    "Hodh El Gharbi Region",
    "Inchiri Region",
    "Nouakchott-Nord Region",
    "Nouakchott-Ouest Region",
    "Nouakchott-Sud Region",
    "Tagant Region",
    "Tiris Zemmour Region",
    "Trarza Region",
  ],
  MS: [
  ],
  MT: [
    "Attard",
    "Balzan",
    "Birgu",
    "Birkirkara",
    "Birżebbuġa",
    "Cospicua",
    "Dingli",
    "Fgura",
    "Floriana",
    "Fontana",
    "Għajnsielem",
    "Għarb",
    "Għargħur",
    "Għasri",
    "Għaxaq",
    "Gudja",
    "Gżira",
    "Ħamrun",
    "Iklin",
    "Kalkara",
    "Kerċem",
    "Kirkop",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsaskala",
    "Marsaxlokk",
    "Mdina",
    "Mellieħa",
    "Mġarr",
    "Mosta",
    "Mqabba",
    "Msida",
    "Mtarfa",
    "Munxar",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Pietà",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat",
    "Saint Lawrence",
    "San Ġwann",
    "Sannat",
    "Santa Luċija",
    "Santa Venera",
    "Senglea",
    "Siġġiewi",
    "Sliema",
    "St. Julian's",
    "St. Paul's Bay",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Valletta",
    "Victoria",
    "Xagħra",
    "Xewkija",
    "Xgħajra",
    "Żabbar",
    "Żebbuġ Gozo",
    "Żebbuġ Malta",
    "Żejtun",
    "Żurrieq",
  ],
  MU: [
    "Agaléga",
    "Beau Bassin-Rose Hill",
    "Cargados Carajos",
    "Curepipe",
    "Flacq District",
    "Grand Port District",
    "Moka District",
    "Pamplemousses District",
    "Plaines Wilhems District",
    "Port Louis",
    "Port Louis District",
    "Quatre Bornes",
    "Rivière du Rempart District",
    "Rivière Noire District",
    "Rodrigues",
    "Savanne District",
    "Vacoas-Phoenix",
  ],
  MV: [
    "Addu Atoll",
    "Alif Alif Atoll",
    "Alif Dhaal Atoll",
    "Central Province",
    "Dhaalu Atoll",
    "Faafu Atoll",
    "Gaafu Alif Atoll",
    "Gaafu Dhaalu Atoll",
    "Gnaviyani Atoll",
    "Haa Alif Atoll",
    "Haa Dhaalu Atoll",
    "Kaafu Atoll",
    "Laamu Atoll",
    "Lhaviyani Atoll",
    "Malé",
    "Meemu Atoll",
    "Noonu Atoll",
    "North Central Province",
    "North Province",
    "Raa Atoll",
    "Shaviyani Atoll",
    "South Central Province",
    "South Province",
    "Thaa Atoll",
    "Upper South Province",
    "Vaavu Atoll",
  ],
  MW: [
    "Balaka District",
    "Blantyre District",
    "Central Region",
    "Chikwawa District",
    "Chiradzulu District",
    "Chitipa district",
    "Dedza District",
    "Dowa District",
    "Karonga District",
    "Kasungu District",
    "Likoma District",
    "Lilongwe District",
    "Machinga District",
    "Mangochi District",
    "Mchinji District",
    "Mulanje District",
    "Mwanza District",
    "Mzimba District",
    "Nkhata Bay District",
    "Nkhotakota District",
    "Northern Region",
    "Nsanje District",
    "Ntcheu District",
    "Ntchisi District",
    "Phalombe District",
    "Rumphi District",
    "Salima District",
    "Southern Region",
    "Thyolo District",
    "Zomba District",
  ],
  MX: [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Ciudad de Mexico",
    "Coahuila",
    "Colima",
    "Durango",
    "Estado de Mexico",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Michoacan",
    "Morelos",
    "Nayarit",
    "Nuevo Leon",
    "Oaxaca",
    "Puebla",
    "Queretaro",
    "Quintana Roo",
    "San Luis Potosi",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatan",
    "Zacatecas",
  ],
  MY: [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Labuan",
    "Malacca",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Putrajaya",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
  ],
  MZ: [
    "Cabo Delgado Province",
    "Gaza Province",
    "Inhambane Province",
    "Manica Province",
    "Maputo",
    "Maputo Province",
    "Nampula Province",
    "Niassa Province",
    "Sofala Province",
    "Tete Province",
    "Zambezia Province",
  ],
  NA: [
    "Erongo Region",
    "Hardap Region",
    "Karas Region",
    "Kavango East Region",
    "Kavango West Region",
    "Khomas Region",
    "Kunene Region",
    "Ohangwena Region",
    "Omaheke Region",
    "Omusati Region",
    "Oshana Region",
    "Oshikoto Region",
    "Otjozondjupa Region",
    "Zambezi Region",
  ],
  NC: [
  ],
  NE: [
    "Agadez Region",
    "Diffa Region",
    "Dosso Region",
    "Maradi Region",
    "Tahoua Region",
    "Tillabéri Region",
    "Zinder Region",
  ],
  NF: [
  ],
  NG: [
    "Abia",
    "Abuja Federal Capital Territory",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  NI: [
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Costa Caribe Norte",
    "Costa Caribe Sur",
    "Esteli",
    "Granada",
    "Jinotega",
    "Leon",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Rio San Juan",
    "Rivas",
  ],
  NL: [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
  ],
  NO: [
    "Agder",
    "Akershus",
    "Buskerud",
    "Finnmark",
    "Innlandet",
    "More og Romsdal",
    "Nordland",
    "Oslo",
    "Ostfold",
    "Rogaland",
    "Telemark",
    "Troms",
    "Trondelag",
    "Vestfold",
    "Vestland",
  ],
  NP: [
    "Bagmati Zone",
    "Bheri Zone",
    "Central Region",
    "Dhaulagiri Zone",
    "Eastern Development Region",
    "Far-Western Development Region",
    "Gandaki Zone",
    "Janakpur Zone",
    "Karnali Zone",
    "Kosi Zone",
    "Lumbini Zone",
    "Mahakali Zone",
    "Mechi Zone",
    "Mid-Western Region",
    "Narayani Zone",
    "Rapti Zone",
    "Sagarmatha Zone",
    "Seti Zone",
    "Western Region",
  ],
  NR: [
    "Aiwo District",
    "Anabar District",
    "Anetan District",
    "Anibare District",
    "Baiti District",
    "Boe District",
    "Buada District",
    "Denigomodu District",
    "Ewa District",
    "Ijuw District",
    "Meneng District",
    "Nibok District",
    "Uaboe District",
    "Yaren District",
  ],
  NU: [
  ],
  NZ: [
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Gisborne",
    "Hawke Bay",
    "Manawatu-Wanganui",
    "Marlborough",
    "Nelson",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Tasman",
    "Waikato",
    "Wellington",
    "West Coast",
  ],
  OM: [
    "Ad Dakhiliyah Governorate",
    "Ad Dhahirah Governorate",
    "Al Batinah North Governorate",
    "Al Batinah Region",
    "Al Batinah South Governorate",
    "Al Buraimi Governorate",
    "Al Wusta Governorate",
    "Ash Sharqiyah North Governorate",
    "Ash Sharqiyah Region",
    "Ash Sharqiyah South Governorate",
    "Dhofar Governorate",
    "Musandam Governorate",
    "Muscat Governorate",
  ],
  PA: [
    "Bocas del Toro",
    "Chiriqui",
    "Cocle",
    "Colon",
    "Darien",
    "Embera-Wounaan",
    "Guna Yala",
    "Herrera",
    "Los Santos",
    "Ngabe-Bugle",
    "Panama",
    "Panama Oeste",
    "Veraguas",
  ],
  PE: [
    "Amazonas",
    "Áncash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cusco",
    "Huancavelica",
    "Huanuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali",
  ],
  PF: [
  ],
  PG: [
    "Bougainville",
    "Central Province",
    "Chimbu Province",
    "East New Britain",
    "Eastern Highlands Province",
    "Enga Province",
    "Gulf",
    "Hela",
    "Jiwaka Province",
    "Madang Province",
    "Manus Province",
    "Milne Bay Province",
    "Morobe Province",
    "New Ireland Province",
    "Oro Province",
    "Port Moresby",
    "Sandaun Province",
    "Southern Highlands Province",
    "West New Britain Province",
    "Western Highlands Province",
    "Western Province",
  ],
  PH: [
    "Abra",
    "Agusan del Norte",
    "Agusan del Sur",
    "Aklan",
    "Albay",
    "Antique",
    "Apayao",
    "Aurora",
    "Autonomous Region in Muslim Mindanao",
    "Basilan",
    "Bataan",
    "Batanes",
    "Batangas",
    "Benguet",
    "Bicol Region",
    "Biliran",
    "Bohol",
    "Bukidnon",
    "Bulacan",
    "Cagayan",
    "Cagayan Valley",
    "Calabarzon",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguin",
    "Capiz",
    "Caraga",
    "Catanduanes",
    "Cavite",
    "Cebu",
    "Central Luzon",
    "Central Visayas",
    "Compostela Valley",
    "Cordillera Administrative Region",
    "Cotabato",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Davao Region",
    "Dinagat Islands",
    "Eastern Samar",
    "Eastern Visayas",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Region",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Kalinga",
    "La Union",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "Leyte",
    "Maguindanao",
    "Marinduque",
    "Masbate",
    "Metro Manila",
    "Mimaropa",
    "Misamis Occidental",
    "Misamis Oriental",
    "Mountain Province",
    "Negros Occidental",
    "Negros Oriental",
    "Northern Mindanao",
    "Northern Samar",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Quezon",
    "Quirino",
    "Rizal",
    "Romblon",
    "Sarangani",
    "Siquijor",
    "Soccsksargen",
    "Sorsogon",
    "South Cotabato",
    "Southern Leyte",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tarlac",
    "Tawi-Tawi",
    "Western Visayas",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Peninsula",
    "Zamboanga Sibugay",
  ],
  PK: [
    "Azad Kashmir",
    "Balochistan",
    "Gilgit-Baltistan",
    "Islamabad Capital Territory",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh",
  ],
  PL: [
    "Greater Poland",
    "Kuyavian-Pomeranian",
    "Lesser Poland",
    "Lodz",
    "Lower Silesian",
    "Lublin",
    "Lubusz",
    "Masovian",
    "Opole",
    "Podkarpackie",
    "Podlaskie",
    "Pomeranian",
    "Silesian",
    "Swietokrzyskie",
    "Warmian-Masurian",
    "West Pomeranian",
  ],
  PM: [
  ],
  PN: [
  ],
  PR: [
  ],
  PS: [
  ],
  PT: [
    "Aveiro",
    "Beja",
    "Braga",
    "Braganca",
    "Castelo Branco",
    "Coimbra",
    "Evora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisboa",
    "Madeira",
    "Portalegre",
    "Porto",
    "Santarem",
    "Setubal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
  ],
  PW: [
    "Aimeliik",
    "Airai",
    "Angaur",
    "Hatohobei",
    "Kayangel",
    "Koror",
    "Melekeok",
    "Ngaraard",
    "Ngarchelong",
    "Ngardmau",
    "Ngatpang",
    "Ngchesar",
    "Ngeremlengui",
    "Ngiwal",
    "Peleliu",
    "Sonsorol",
  ],
  PY: [
    "Alto Paraguay Department",
    "Alto Paraná Department",
    "Amambay Department",
    "Boquerón Department",
    "Caaguazú",
    "Caazapá",
    "Canindeyú",
    "Central Department",
    "Concepción Department",
    "Cordillera Department",
    "Guairá Department",
    "Itapúa",
    "Misiones Department",
    "Ñeembucú Department",
    "Paraguarí Department",
    "Presidente Hayes Department",
    "San Pedro Department",
  ],
  QA: [
    "Al Daayen",
    "Al Khor",
    "Al Rayyan Municipality",
    "Al Wakrah",
    "Al-Shahaniya",
    "Doha",
    "Madinat ash Shamal",
    "Umm Salal Municipality",
  ],
  RE: [
  ],
  RO: [
    "Alba",
    "Arad",
    "Arges",
    "Bacau",
    "Bihor",
    "Bistrita-Nasaud",
    "Botosani",
    "Brasov",
    "Bucharest",
    "Buzau",
    "Cluj",
    "Constanta",
    "Dolj",
    "Galati",
    "Iasi",
    "Maramures",
    "Mures",
    "Prahova",
    "Sibiu",
    "Timis",
  ],
  RS: [
    "Belgrade",
    "Bor District",
    "Braničevo District",
    "Central Banat District",
    "Jablanica District",
    "Kolubara District",
    "Mačva District",
    "Moravica District",
    "Nišava District",
    "North Bačka District",
    "North Banat District",
    "Pčinja District",
    "Pirot District",
    "Podunavlje District",
    "Pomoravlje District",
    "Rasina District",
    "Raška District",
    "South Bačka District",
    "South Banat District",
    "Srem District",
    "Šumadija District",
    "Toplica District",
    "Vojvodina",
    "West Bačka District",
    "Zaječar District",
    "Zlatibor District",
  ],
  RU: [
    "Altai Krai",
    "Altai Republic",
    "Amur Oblast",
    "Arkhangelsk",
    "Astrakhan Oblast",
    "Belgorod Oblast",
    "Bryansk Oblast",
    "Chechen Republic",
    "Chelyabinsk Oblast",
    "Chukotka Autonomous Okrug",
    "Chuvash Republic",
    "Irkutsk",
    "Ivanovo Oblast",
    "Jewish Autonomous Oblast",
    "Kabardino-Balkar Republic",
    "Kaliningrad",
    "Kaluga Oblast",
    "Kamchatka Krai",
    "Karachay-Cherkess Republic",
    "Kemerovo Oblast",
    "Khabarovsk Krai",
    "Khanty-Mansi Autonomous Okrug",
    "Kirov Oblast",
    "Komi Republic",
    "Kostroma Oblast",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Kurgan Oblast",
    "Kursk Oblast",
    "Leningrad Oblast",
    "Lipetsk Oblast",
    "Magadan Oblast",
    "Mari El Republic",
    "Moscow",
    "Moscow Oblast",
    "Murmansk Oblast",
    "Nenets Autonomous Okrug",
    "Nizhny Novgorod Oblast",
    "Novgorod Oblast",
    "Novosibirsk",
    "Omsk Oblast",
    "Orenburg Oblast",
    "Oryol Oblast",
    "Penza Oblast",
    "Perm Krai",
    "Primorsky Krai",
    "Pskov Oblast",
    "Republic of Adygea",
    "Republic of Bashkortostan",
    "Republic of Buryatia",
    "Republic of Dagestan",
    "Republic of Ingushetia",
    "Republic of Kalmykia",
    "Republic of Karelia",
    "Republic of Khakassia",
    "Republic of Mordovia",
    "Republic of North Ossetia-Alania",
    "Republic of Tatarstan",
    "Rostov Oblast",
    "Ryazan Oblast",
    "Saint Petersburg",
    "Sakha Republic",
    "Sakhalin",
    "Samara Oblast",
    "Saratov Oblast",
    "Sevastopol",
    "Smolensk Oblast",
    "Stavropol Krai",
    "Sverdlovsk",
    "Tambov Oblast",
    "Tomsk Oblast",
    "Tula Oblast",
    "Tuva Republic",
    "Tver Oblast",
    "Tyumen Oblast",
    "Udmurt Republic",
    "Ulyanovsk Oblast",
    "Vladimir Oblast",
    "Vologda Oblast",
    "Voronezh Oblast",
    "Yamalo-Nenets Autonomous Okrug",
    "Yaroslavl Oblast",
    "Zabaykalsky Krai",
  ],
  RW: [
    "Eastern Province",
    "Kigali district",
    "Northern Province",
    "Southern Province",
    "Western Province",
  ],
  SA: [
    "Asir",
    "Eastern Province",
    "Jazan",
    "Madinah",
    "Makkah",
    "Najran",
    "Northern Borders",
    "Qassim",
    "Riyadh",
    "Tabuk",
  ],
  SB: [
    "Central Province",
    "Choiseul Province",
    "Guadalcanal Province",
    "Honiara",
    "Isabel Province",
    "Makira-Ulawa Province",
    "Malaita Province",
    "Rennell and Bellona Province",
    "Temotu Province",
    "Western Province",
  ],
  SC: [
    "Anse Boileau",
    "Anse Royale",
    "Anse-aux-Pins",
    "Au Cap",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "Glacis",
    "Grand'Anse Mahé",
    "Grand'Anse Praslin",
    "La Digue",
    "La Rivière Anglaise",
    "Les Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Roche Caiman",
    "Saint Louis",
    "Takamaka",
  ],
  SD: [
    "Al Jazirah",
    "Al Qadarif",
    "Blue Nile",
    "Central Darfur",
    "East Darfur",
    "Kassala",
    "Khartoum",
    "North Darfur",
    "North Kordofan",
    "Northern",
    "Red Sea",
    "River Nile",
    "Sennar",
    "South Darfur",
    "South Kordofan",
    "West Darfur",
    "West Kordofan",
    "White Nile",
  ],
  SE: [
    "Blekinge",
    "Dalarna",
    "Gavleborg",
    "Gotland",
    "Halland",
    "Jamtland",
    "Jonkoping",
    "Kalmar",
    "Kronoberg",
    "Norrbotten",
    "Orebro",
    "Ostergotland",
    "Skane",
    "Sodermanland",
    "Stockholm",
    "Uppsala",
    "Varmland",
    "Vasterbotten",
    "Vasternorrland",
    "Vastmanland",
    "Vastra Gotaland",
  ],
  SG: [
    "Central Singapore",
    "North East",
    "North West",
    "South East",
    "South West",
  ],
  SH: [
  ],
  SI: [
    "Ajdovščina Municipality",
    "Ankaran Municipality",
    "Beltinci Municipality",
    "Benedikt Municipality",
    "Bistrica ob Sotli Municipality",
    "Bled Municipality",
    "Bloke Municipality",
    "Bohinj Municipality",
    "Borovnica Municipality",
    "Bovec Municipality",
    "Braslovče Municipality",
    "Brda Municipality",
    "Brežice Municipality",
    "Brezovica Municipality",
    "Cankova Municipality",
    "Cerklje na Gorenjskem Municipality",
    "Cerknica Municipality",
    "Cerkno Municipality",
    "Cerkvenjak Municipality",
    "City Municipality of Celje",
    "City Municipality of Novo Mesto",
    "Črenšovci Municipality",
    "Črna na Koroškem Municipality",
    "Črnomelj Municipality",
    "Destrnik Municipality",
    "Divača Municipality",
    "Dobje Municipality",
    "Dobrepolje Municipality",
    "Dobrna Municipality",
    "Dobrova–Polhov Gradec Municipality",
    "Dobrovnik Municipality",
    "Dol pri Ljubljani Municipality",
    "Dolenjske Toplice Municipality",
    "Domžale Municipality",
    "Dornava Municipality",
    "Dravograd Municipality",
    "Duplek Municipality",
    "Gorenja Vas–Poljane Municipality",
    "Gorišnica Municipality",
    "Gorje Municipality",
    "Gornja Radgona Municipality",
    "Gornji Grad Municipality",
    "Gornji Petrovci Municipality",
    "Grad Municipality",
    "Grosuplje Municipality",
    "Hajdina Municipality",
    "Hoče–Slivnica Municipality",
    "Hodoš Municipality",
    "Horjul Municipality",
    "Hrastnik Municipality",
    "Hrpelje–Kozina Municipality",
    "Idrija Municipality",
    "Ig Municipality",
    "Ivančna Gorica Municipality",
    "Izola Municipality",
    "Jesenice Municipality",
    "Jezersko Municipality",
    "Juršinci Municipality",
    "Kamnik Municipality",
    "Kanal ob Soči Municipality",
    "Kidričevo Municipality",
    "Kobarid Municipality",
    "Kobilje Municipality",
    "Kočevje Municipality",
    "Komen Municipality",
    "Komenda Municipality",
    "Koper City Municipality",
    "Kostanjevica na Krki Municipality",
    "Kostel Municipality",
    "Kozje Municipality",
    "Kranj City Municipality",
    "Kranjska Gora Municipality",
    "Križevci Municipality",
    "Kungota",
    "Kuzma Municipality",
    "Laško Municipality",
    "Lenart Municipality",
    "Lendava Municipality",
    "Litija Municipality",
    "Ljubljana City Municipality",
    "Ljubno Municipality",
    "Ljutomer Municipality",
    "Log–Dragomer Municipality",
    "Logatec Municipality",
    "Loška Dolina Municipality",
    "Loški Potok Municipality",
    "Lovrenc na Pohorju Municipality",
    "Luče Municipality",
    "Lukovica Municipality",
    "Majšperk Municipality",
    "Makole Municipality",
    "Maribor City Municipality",
    "Markovci Municipality",
    "Medvode Municipality",
    "Mengeš Municipality",
    "Metlika Municipality",
    "Mežica Municipality",
    "Miklavž na Dravskem Polju Municipality",
    "Miren–Kostanjevica Municipality",
    "Mirna Municipality",
    "Mirna Peč Municipality",
    "Mislinja Municipality",
    "Mokronog–Trebelno Municipality",
    "Moravče Municipality",
    "Moravske Toplice Municipality",
    "Mozirje Municipality",
    "Municipality of Apače",
    "Municipality of Cirkulane",
    "Municipality of Ilirska Bistrica",
    "Municipality of Krško",
    "Municipality of Škofljica",
    "Murska Sobota City Municipality",
    "Muta Municipality",
    "Naklo Municipality",
    "Nazarje Municipality",
    "Nova Gorica City Municipality",
    "Odranci Municipality",
    "Oplotnica",
    "Ormož Municipality",
    "Osilnica Municipality",
    "Pesnica Municipality",
    "Piran Municipality",
    "Pivka Municipality",
    "Podčetrtek Municipality",
    "Podlehnik Municipality",
    "Podvelka Municipality",
    "Poljčane Municipality",
    "Polzela Municipality",
    "Postojna Municipality",
    "Prebold Municipality",
    "Preddvor Municipality",
    "Prevalje Municipality",
    "Ptuj City Municipality",
    "Puconci Municipality",
    "Rače–Fram Municipality",
    "Radeče Municipality",
    "Radenci Municipality",
    "Radlje ob Dravi Municipality",
    "Radovljica Municipality",
    "Ravne na Koroškem Municipality",
    "Razkrižje Municipality",
    "Rečica ob Savinji Municipality",
    "Renče–Vogrsko Municipality",
    "Ribnica Municipality",
    "Ribnica na Pohorju Municipality",
    "Rogaška Slatina Municipality",
    "Rogašovci Municipality",
    "Rogatec Municipality",
    "Ruše Municipality",
    "Šalovci Municipality",
    "Selnica ob Dravi Municipality",
    "Semič Municipality",
    "Šempeter–Vrtojba Municipality",
    "Šenčur Municipality",
    "Šentilj Municipality",
    "Šentjernej Municipality",
    "Šentjur Municipality",
    "Šentrupert Municipality",
    "Sevnica Municipality",
    "Sežana Municipality",
    "Škocjan Municipality",
    "Škofja Loka Municipality",
    "Slovenj Gradec City Municipality",
    "Slovenska Bistrica Municipality",
    "Slovenske Konjice Municipality",
    "Šmarje pri Jelšah Municipality",
    "Šmarješke Toplice Municipality",
    "Šmartno ob Paki Municipality",
    "Šmartno pri Litiji Municipality",
    "Sodražica Municipality",
    "Solčava Municipality",
    "Šoštanj Municipality",
    "Središče ob Dravi",
    "Starše Municipality",
    "Štore Municipality",
    "Straža Municipality",
    "Sveta Ana Municipality",
    "Sveta Trojica v Slovenskih Goricah Municipality",
    "Sveti Andraž v Slovenskih Goricah Municipality",
    "Sveti Jurij ob Ščavnici Municipality",
    "Sveti Jurij v Slovenskih Goricah Municipality",
    "Sveti Tomaž Municipality",
    "Tabor Municipality",
    "Tišina Municipality",
    "Tolmin Municipality",
    "Trbovlje Municipality",
    "Trebnje Municipality",
    "Trnovska Vas Municipality",
    "Tržič Municipality",
    "Trzin Municipality",
    "Turnišče Municipality",
    "Velika Polana Municipality",
    "Velike Lašče Municipality",
    "Veržej Municipality",
    "Videm Municipality",
    "Vipava Municipality",
    "Vitanje Municipality",
    "Vodice Municipality",
    "Vojnik Municipality",
    "Vransko Municipality",
    "Vrhnika Municipality",
    "Vuzenica Municipality",
    "Zagorje ob Savi Municipality",
    "Žalec Municipality",
    "Zavrč Municipality",
    "Železniki Municipality",
    "Žetale Municipality",
    "Žiri Municipality",
    "Žirovnica Municipality",
    "Zreče Municipality",
    "Žužemberk Municipality",
  ],
  SJ: [
  ],
  SK: [
    "Banská Bystrica Region",
    "Bratislava Region",
    "Košice Region",
    "Nitra Region",
    "Prešov Region",
    "Trenčín Region",
    "Trnava Region",
    "Žilina Region",
  ],
  SL: [
    "Eastern Province",
    "Northern Province",
    "Southern Province",
    "Western Area",
  ],
  SM: [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle",
  ],
  SN: [
    "Dakar",
    "Diourbel Region",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda Region",
    "Thiès Region",
    "Ziguinchor",
  ],
  SO: [
    "Awdal Region",
    "Bakool",
    "Banaadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiran",
    "Lower Juba",
    "Lower Shebelle",
    "Middle Juba",
    "Middle Shebelle",
    "Mudug",
    "Nugal",
    "Sanaag Region",
    "Togdheer Region",
  ],
  SR: [
    "Brokopondo District",
    "Commewijne District",
    "Coronie District",
    "Marowijne District",
    "Nickerie District",
    "Para District",
    "Paramaribo District",
    "Saramacca District",
    "Sipaliwini District",
    "Wanica District",
  ],
  SS: [
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei State",
    "Lakes",
    "Northern Bahr el Ghazal",
    "Unity",
    "Upper Nile",
    "Warrap",
    "Western Bahr el Ghazal",
    "Western Equatoria",
  ],
  ST: [
    "Príncipe Province",
    "São Tomé Province",
  ],
  SV: [
    "Ahuachapan",
    "Cabanas",
    "Chalatenango",
    "Cuscatlan",
    "La Libertad",
    "La Paz",
    "La Union",
    "Morazan",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulutan",
  ],
  SY: [
    "Al-Hasakah Governorate",
    "Al-Raqqah Governorate",
    "Aleppo Governorate",
    "As-Suwayda Governorate",
    "Damascus Governorate",
    "Daraa Governorate",
    "Deir ez-Zor Governorate",
    "Hama Governorate",
    "Homs Governorate",
    "Idlib Governorate",
    "Latakia Governorate",
    "Quneitra Governorate",
    "Rif Dimashq Governorate",
    "Tartus Governorate",
  ],
  SZ: [
    "Hhohho District",
    "Lubombo District",
    "Manzini District",
    "Shiselweni District",
  ],
  TC: [
  ],
  TD: [
    "Bahr el Gazel",
    "Batha Region",
    "Borkou",
    "Ennedi Region",
    "Ennedi-Est",
    "Ennedi-Ouest",
    "Guéra Region",
    "Hadjer-Lamis",
    "Kanem Region",
    "Lac Region",
    "Logone Occidental Region",
    "Logone Oriental Region",
    "Mandoul Region",
    "Mayo-Kebbi Est Region",
    "Mayo-Kebbi Ouest Region",
    "Moyen-Chari Region",
    "N'Djamena",
    "Ouaddaï Region",
    "Salamat Region",
    "Sila Region",
    "Tandjilé Region",
    "Tibesti Region",
    "Wadi Fira Region",
  ],
  TF: [
  ],
  TG: [
    "Centrale Region",
    "Kara Region",
    "Maritime",
    "Plateaux Region",
    "Savanes Region",
  ],
  TH: [
    "Bangkok",
    "Chiang Mai",
    "Chon Buri",
    "Krabi",
    "Nakhon Ratchasima",
    "Nonthaburi",
    "Pathum Thani",
    "Phuket",
    "Samut Prakan",
    "Songkhla",
    "Surat Thani",
  ],
  TJ: [
    "districts of Republican Subordination",
    "Gorno-Badakhshan Autonomous Province",
    "Khatlon Province",
    "Sughd Province",
  ],
  TK: [
  ],
  TL: [
    "Aileu municipality",
    "Ainaro Municipality",
    "Baucau Municipality",
    "Bobonaro Municipality",
    "Cova Lima Municipality",
    "Dili municipality",
    "Ermera District",
    "Lautém Municipality",
    "Liquiçá Municipality",
    "Manatuto District",
    "Manufahi Municipality",
    "Viqueque Municipality",
  ],
  TM: [
    "Ahal Region",
    "Ashgabat",
    "Balkan Region",
    "Daşoguz Region",
    "Lebap Region",
    "Mary Region",
  ],
  TN: [
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Le Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan",
  ],
  TO: [
    "Haʻapai",
    "ʻEua",
    "Niuas",
    "Tongatapu",
    "Vavaʻu",
  ],
  TR: [
    "Adana",
    "Ankara",
    "Antalya",
    "Bursa",
    "Gaziantep",
    "Istanbul",
    "Izmir",
    "Kayseri",
    "Kocaeli",
    "Konya",
    "Mersin",
    "Sakarya",
    "Samsun",
  ],
  TT: [
    "Arima",
    "Chaguanas",
    "Couva-Tabaquite-Talparo Regional Corporation",
    "Diego Martin Regional Corporation",
    "Eastern Tobago",
    "Penal-Debe Regional Corporation",
    "Point Fortin",
    "Port of Spain",
    "Princes Town Regional Corporation",
    "Rio Claro-Mayaro Regional Corporation",
    "San Fernando",
    "San Juan-Laventille Regional Corporation",
    "Sangre Grande Regional Corporation",
    "Siparia Regional Corporation",
    "Tunapuna-Piarco Regional Corporation",
    "Western Tobago",
  ],
  TV: [
    "Funafuti",
    "Nanumanga",
    "Nanumea",
    "Niutao Island Council",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaitupu",
  ],
  TW: [
    "Changhua County",
    "Chiayi City",
    "Chiayi County",
    "Hsinchu",
    "Hsinchu County",
    "Hualien County",
    "Kaohsiung",
    "Kaohsiung County",
    "Kinmen",
    "Lienchiang County",
    "Miaoli County",
    "Nantou County",
    "Penghu County",
    "Pingtung County",
    "Taichung",
    "Taichung County",
    "Tainan",
    "Tainan County",
    "Taipei",
    "Taitung County",
    "Taoyuan City",
    "Yilan County",
    "Yunlin County",
  ],
  TZ: [
    "Arusha Region",
    "Dar es Salaam Region",
    "Dodoma Region",
    "Geita Region",
    "Iringa Region",
    "Kagera Region",
    "Katavi Region",
    "Kigoma Region",
    "Kilimanjaro Region",
    "Lindi Region",
    "Manyara Region",
    "Mara Region",
    "Morogoro Region",
    "Mtwara Region",
    "Mwanza Region",
    "Njombe Region",
    "North Pemba Region",
    "Pwani Region",
    "Rukwa Region",
    "Ruvuma Region",
    "Shinyanga Region",
    "Simiyu Region",
    "Singida Region",
    "South Pemba Region",
    "Tabora Region",
    "Tanga Region",
    "Zanzibar Central South Region",
    "Zanzibar North Region",
    "Zanzibar Urban West Region",
  ],
  UA: [
    "Cherkasy",
    "Chernihiv",
    "Chernivtsi",
    "Dnipropetrovsk",
    "Donetsk",
    "Ivano-Frankivsk",
    "Kharkiv",
    "Kherson",
    "Khmelnytskyi",
    "Kirovohrad",
    "Kyiv",
    "Luhansk",
    "Lviv",
    "Mykolaiv",
    "Odesa",
    "Poltava",
    "Rivne",
    "Sumy",
    "Ternopil",
    "Vinnytsia",
    "Volyn",
    "Zakarpattia",
    "Zaporizhzhia",
    "Zhytomyr",
  ],
  UG: [
    "Abim District",
    "Adjumani District",
    "Agago District",
    "Alebtong District",
    "Amolatar District",
    "Amudat District",
    "Amuria District",
    "Amuru District",
    "Apac District",
    "Arua District",
    "Budaka District",
    "Bududa District",
    "Bugiri District",
    "Buhweju District",
    "Buikwe District",
    "Bukedea District",
    "Bukomansimbi District",
    "Bukwo District",
    "Bulambuli District",
    "Buliisa District",
    "Bundibugyo District",
    "Bunyangabu District",
    "Bushenyi District",
    "Busia District",
    "Butaleja District",
    "Butambala District",
    "Butebo District",
    "Buvuma District",
    "Buyende District",
    "Central Region",
    "Dokolo District",
    "Eastern Region",
    "Gomba District",
    "Gulu District",
    "Ibanda District",
    "Iganga District",
    "Isingiro District",
    "Jinja District",
    "Kaabong District",
    "Kabale District",
    "Kabarole District",
    "Kaberamaido District",
    "Kagadi District",
    "Kakumiro District",
    "Kalangala District",
    "Kaliro District",
    "Kalungu District",
    "Kampala District",
    "Kamuli District",
    "Kamwenge District",
    "Kanungu District",
    "Kapchorwa District",
    "Kasese District",
    "Katakwi District",
    "Kayunga District",
    "Kibaale District",
    "Kiboga District",
    "Kibuku District",
    "Kiruhura District",
    "Kiryandongo District",
    "Kisoro District",
    "Kitgum District",
    "Koboko District",
    "Kole District",
    "Kotido District",
    "Kumi District",
    "Kween District",
    "Kyankwanzi District",
    "Kyegegwa District",
    "Kyenjojo District",
    "Kyotera District",
    "Lamwo District",
    "Lira District",
    "Luuka District",
    "Luwero District",
    "Lwengo District",
    "Lyantonde District",
    "Manafwa District",
    "Maracha District",
    "Masaka District",
    "Masindi District",
    "Mayuge District",
    "Mbale District",
    "Mbarara District",
    "Mitooma District",
    "Mityana District",
    "Moroto District",
    "Moyo District",
    "Mpigi District",
    "Mubende District",
    "Mukono District",
    "Nakapiripirit District",
    "Nakaseke District",
    "Nakasongola District",
    "Namayingo District",
    "Namisindwa District",
    "Namutumba District",
    "Napak District",
    "Nebbi District",
    "Ngora District",
    "Northern Region",
    "Ntoroko District",
    "Ntungamo District",
    "Nwoya District",
    "Omoro District",
    "Otuke District",
    "Oyam District",
    "Pader District",
    "Pakwach District",
    "Pallisa District",
    "Rakai District",
    "Rubanda District",
    "Rubirizi District",
    "Rukiga District",
    "Rukungiri District",
    "Sembabule District",
    "Serere District",
    "Sheema District",
    "Sironko District",
    "Soroti District",
    "Tororo District",
    "Wakiso District",
    "Western Region",
    "Yumbe District",
    "Zombo District",
  ],
  UM: [
  ],
  US: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  UY: [
    "Artigas Department",
    "Canelones Department",
    "Cerro Largo Department",
    "Colonia Department",
    "Durazno Department",
    "Flores Department",
    "Florida Department",
    "Lavalleja Department",
    "Maldonado Department",
    "Montevideo Department",
    "Paysandú Department",
    "Río Negro Department",
    "Rivera Department",
    "Rocha Department",
    "Salto Department",
    "San José Department",
    "Soriano Department",
    "Tacuarembó Department",
    "Treinta y Tres Department",
  ],
  UZ: [
    "Andijan Region",
    "Bukhara Region",
    "Fergana Region",
    "Jizzakh Region",
    "Karakalpakstan",
    "Namangan Region",
    "Navoiy Region",
    "Qashqadaryo Region",
    "Samarqand Region",
    "Sirdaryo Region",
    "Surxondaryo Region",
    "Tashkent",
    "Tashkent Region",
    "Xorazm Region",
  ],
  VA: [
  ],
  VC: [
    "Charlotte Parish",
    "Grenadines Parish",
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint Patrick Parish",
  ],
  VE: [
    "Amazonas",
    "Anzoategui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolivar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Distrito Capital",
    "Falcon",
    "Guarico",
    "La Guaira",
    "Lara",
    "Merida",
    "Miranda",
    "Monagas",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Tachira",
    "Trujillo",
    "Yaracuy",
    "Zulia",
  ],
  VG: [
  ],
  VI: [
  ],
  VN: [
    "An Giang",
    "Ba Ria-Vung Tau",
    "Bac Giang",
    "Binh Duong",
    "Can Tho",
    "Da Nang",
    "Dong Nai",
    "Ha Noi",
    "Hai Phong",
    "Ho Chi Minh City",
    "Khanh Hoa",
    "Lam Dong",
    "Long An",
    "Quang Nam",
    "Thua Thien Hue",
  ],
  VU: [
    "Malampa",
    "Penama",
    "Sanma",
    "Shefa",
    "Tafea",
    "Torba",
  ],
  WF: [
  ],
  WS: [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gaga'ifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano",
  ],
  XK: [
    "Đakovica District (Gjakove)",
    "Gjilan District",
    "Kosovska Mitrovica District",
    "Peć District",
    "Pristina (Priştine)",
    "Prizren District",
    "Uroševac District (Ferizaj)",
  ],
  YE: [
    "'Adan Governorate",
    "'Amran Governorate",
    "Abyan Governorate",
    "Al Bayda' Governorate",
    "Al Hudaydah Governorate",
    "Al Jawf Governorate",
    "Al Mahrah Governorate",
    "Al Mahwit Governorate",
    "Dhamar Governorate",
    "Hadhramaut Governorate",
    "Hajjah Governorate",
    "Ibb Governorate",
    "Lahij Governorate",
    "Ma'rib Governorate",
    "Raymah Governorate",
    "Saada Governorate",
    "Sana'a",
    "Sana'a Governorate",
    "Shabwah Governorate",
    "Socotra Governorate",
    "Ta'izz Governorate",
  ],
  YT: [
  ],
  ZA: [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
  ],
  ZM: [
    "Central Province",
    "Copperbelt Province",
    "Eastern Province",
    "Luapula Province",
    "Lusaka Province",
    "Muchinga Province",
    "Northern Province",
    "Northwestern Province",
    "Southern Province",
    "Western Province",
  ],
  ZW: [
    "Bulawayo Province",
    "Harare Province",
    "Manicaland",
    "Mashonaland Central Province",
    "Mashonaland East Province",
    "Mashonaland West Province",
    "Masvingo Province",
    "Matabeleland North Province",
    "Matabeleland South Province",
    "Midlands Province",
  ],
};
