export const TECH_SPECIALTY_OPTIONS = [
  'Plomero',
  'Sanitarista',
  'Gasista',
  'Electricista',
  'Albanil',
  'Pintor',
  'Durlockero',
  'Yesero',
  'Carpintero',
  'Herrero',
  'Cerrajero',
  'Techista',
  'Impermeabilizador',
  'Colocador de pisos',
  'Colocador de revestimientos',
  'Vidriero',
  'Instalador de aberturas',
  'Soldador',
  'Instalador de aire acondicionado',
  'Tecnico en refrigeracion',
  'Tecnico calefaccionista',
  'Instalador de portones automaticos',
  'Instalador de alarmas y camaras',
  'Tecnico en redes y datos',
  'Instalador solar',
  'Jardinero',
  'Podador',
  'Piletero',
  'Fumigador',
  'Limpieza general',
  'Limpieza post obra',
  'Mantenimiento de consorcios',
  'Mantenimiento comercial',
  'Especialista en banos y cocinas',
  'Demoledor',
  'Excavador',
  'Movimiento de suelo',
  'Hormigonista',
  'Estructurista metalico',
  'Reformista integral',
];

export const TECH_SPECIALTY_SEARCH_ALIASES: Record<string, string[]> = {
  Plomero: ['plomeria', 'sanitario', 'canos', 'canerias'],
  Sanitarista: ['sanitario', 'banos', 'bano', 'artefactos sanitarios'],
  Albanil: ['albanileria', 'obra civil'],
  Durlockero: ['durlock', 'durcklero', 'drywall', 'tabiqueria'],
  Yesero: ['yeseria', 'enduido', 'cielorraso'],
  Techista: ['techo', 'cubierta', 'zingueria'],
  Impermeabilizador: ['humedad', 'filtraciones', 'membrana'],
  Piletero: ['piletas', 'piscinas'],
  Fumigador: ['control de plagas'],
};

